// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.cas20200407.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link BatchUpdateNoticeStatusResponseBody} extends {@link TeaModel}
 *
 * <p>BatchUpdateNoticeStatusResponseBody</p>
 */
public class BatchUpdateNoticeStatusResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    private BatchUpdateNoticeStatusResponseBody(Builder builder) {
        this.requestId = builder.requestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static BatchUpdateNoticeStatusResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    public static final class Builder {
        private String requestId; 

        private Builder() {
        } 

        private Builder(BatchUpdateNoticeStatusResponseBody model) {
            this.requestId = model.requestId;
        } 

        /**
         * <p>The ID of the request, which is the unique identifier generated by Alibaba Cloud for the request. The ID can be used to troubleshoot and locate issues.</p>
         * 
         * <strong>example:</strong>
         * <p>3F60357E-76D2-52AD-B3EB-D86276755814</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        public BatchUpdateNoticeStatusResponseBody build() {
            return new BatchUpdateNoticeStatusResponseBody(this);
        } 

    } 

}
