// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.schedulerx320240624.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link GetAppResponseBody} extends {@link TeaModel}
 *
 * <p>GetAppResponseBody</p>
 */
public class GetAppResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("Code")
    private Integer code;

    @com.aliyun.core.annotation.NameInMap("Data")
    private Data data;

    @com.aliyun.core.annotation.NameInMap("Message")
    private String message;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    @com.aliyun.core.annotation.NameInMap("Success")
    private Boolean success;

    private GetAppResponseBody(Builder builder) {
        this.code = builder.code;
        this.data = builder.data;
        this.message = builder.message;
        this.requestId = builder.requestId;
        this.success = builder.success;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static GetAppResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return code
     */
    public Integer getCode() {
        return this.code;
    }

    /**
     * @return data
     */
    public Data getData() {
        return this.data;
    }

    /**
     * @return message
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * @return success
     */
    public Boolean getSuccess() {
        return this.success;
    }

    public static final class Builder {
        private Integer code; 
        private Data data; 
        private String message; 
        private String requestId; 
        private Boolean success; 

        private Builder() {
        } 

        private Builder(GetAppResponseBody model) {
            this.code = model.code;
            this.data = model.data;
            this.message = model.message;
            this.requestId = model.requestId;
            this.success = model.success;
        } 

        /**
         * <p>The response code.</p>
         * 
         * <strong>example:</strong>
         * <p>200</p>
         */
        public Builder code(Integer code) {
            this.code = code;
            return this;
        }

        /**
         * <ul>
         * <li>The details of the application.</li>
         * </ul>
         */
        public Builder data(Data data) {
            this.data = data;
            return this;
        }

        /**
         * <p>The error message.</p>
         * 
         * <strong>example:</strong>
         * <p>Not found: appName not found.</p>
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * <p>The unique ID of the request, generated by Alibaba Cloud. Use this ID to troubleshoot issues.</p>
         * 
         * <strong>example:</strong>
         * <p>D0DE9C33-992A-580B-89C4-B609A292748D</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * <p>Indicates whether the request was successful.</p>
         * 
         * <strong>example:</strong>
         * <p>true</p>
         */
        public Builder success(Boolean success) {
            this.success = success;
            return this;
        }

        public GetAppResponseBody build() {
            return new GetAppResponseBody(this);
        } 

    } 

    /**
     * 
     * {@link GetAppResponseBody} extends {@link TeaModel}
     *
     * <p>GetAppResponseBody</p>
     */
    public static class Data extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("AccessToken")
        private String accessToken;

        @com.aliyun.core.annotation.NameInMap("AppName")
        private String appName;

        @com.aliyun.core.annotation.NameInMap("AppType")
        private Integer appType;

        @com.aliyun.core.annotation.NameInMap("Creator")
        private String creator;

        @com.aliyun.core.annotation.NameInMap("EnableLog")
        private Boolean enableLog;

        @com.aliyun.core.annotation.NameInMap("ExecutorNum")
        private Long executorNum;

        @com.aliyun.core.annotation.NameInMap("Id")
        private Long id;

        @com.aliyun.core.annotation.NameInMap("JobNum")
        private Integer jobNum;

        @com.aliyun.core.annotation.NameInMap("LabelRouteStrategy")
        private Integer labelRouteStrategy;

        @com.aliyun.core.annotation.NameInMap("Leader")
        private String leader;

        @com.aliyun.core.annotation.NameInMap("MaxConcurrency")
        private Integer maxConcurrency;

        @com.aliyun.core.annotation.NameInMap("MaxJobs")
        private Integer maxJobs;

        @com.aliyun.core.annotation.NameInMap("Title")
        private String title;

        @com.aliyun.core.annotation.NameInMap("Updater")
        private String updater;

        private Data(Builder builder) {
            this.accessToken = builder.accessToken;
            this.appName = builder.appName;
            this.appType = builder.appType;
            this.creator = builder.creator;
            this.enableLog = builder.enableLog;
            this.executorNum = builder.executorNum;
            this.id = builder.id;
            this.jobNum = builder.jobNum;
            this.labelRouteStrategy = builder.labelRouteStrategy;
            this.leader = builder.leader;
            this.maxConcurrency = builder.maxConcurrency;
            this.maxJobs = builder.maxJobs;
            this.title = builder.title;
            this.updater = builder.updater;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static Data create() {
            return builder().build();
        }

        /**
         * @return accessToken
         */
        public String getAccessToken() {
            return this.accessToken;
        }

        /**
         * @return appName
         */
        public String getAppName() {
            return this.appName;
        }

        /**
         * @return appType
         */
        public Integer getAppType() {
            return this.appType;
        }

        /**
         * @return creator
         */
        public String getCreator() {
            return this.creator;
        }

        /**
         * @return enableLog
         */
        public Boolean getEnableLog() {
            return this.enableLog;
        }

        /**
         * @return executorNum
         */
        public Long getExecutorNum() {
            return this.executorNum;
        }

        /**
         * @return id
         */
        public Long getId() {
            return this.id;
        }

        /**
         * @return jobNum
         */
        public Integer getJobNum() {
            return this.jobNum;
        }

        /**
         * @return labelRouteStrategy
         */
        public Integer getLabelRouteStrategy() {
            return this.labelRouteStrategy;
        }

        /**
         * @return leader
         */
        public String getLeader() {
            return this.leader;
        }

        /**
         * @return maxConcurrency
         */
        public Integer getMaxConcurrency() {
            return this.maxConcurrency;
        }

        /**
         * @return maxJobs
         */
        public Integer getMaxJobs() {
            return this.maxJobs;
        }

        /**
         * @return title
         */
        public String getTitle() {
            return this.title;
        }

        /**
         * @return updater
         */
        public String getUpdater() {
            return this.updater;
        }

        public static final class Builder {
            private String accessToken; 
            private String appName; 
            private Integer appType; 
            private String creator; 
            private Boolean enableLog; 
            private Long executorNum; 
            private Long id; 
            private Integer jobNum; 
            private Integer labelRouteStrategy; 
            private String leader; 
            private Integer maxConcurrency; 
            private Integer maxJobs; 
            private String title; 
            private String updater; 

            private Builder() {
            } 

            private Builder(Data model) {
                this.accessToken = model.accessToken;
                this.appName = model.appName;
                this.appType = model.appType;
                this.creator = model.creator;
                this.enableLog = model.enableLog;
                this.executorNum = model.executorNum;
                this.id = model.id;
                this.jobNum = model.jobNum;
                this.labelRouteStrategy = model.labelRouteStrategy;
                this.leader = model.leader;
                this.maxConcurrency = model.maxConcurrency;
                this.maxJobs = model.maxJobs;
                this.title = model.title;
                this.updater = model.updater;
            } 

            /**
             * <p>The access token.</p>
             * 
             * <strong>example:</strong>
             * <p>2f4ddeab8e344ed68e0402cf9b8502ffv3</p>
             */
            public Builder accessToken(String accessToken) {
                this.accessToken = accessToken;
                return this;
            }

            /**
             * <p>The application name.</p>
             * 
             * <strong>example:</strong>
             * <p>test-app</p>
             */
            public Builder appName(String appName) {
                this.appName = appName;
                return this;
            }

            /**
             * <p>The application type.</p>
             * 
             * <strong>example:</strong>
             * <p>1</p>
             */
            public Builder appType(Integer appType) {
                this.appType = appType;
                return this;
            }

            /**
             * <p>The creator of the application.</p>
             * 
             * <strong>example:</strong>
             * <p>18582193685027xx</p>
             */
            public Builder creator(String creator) {
                this.creator = creator;
                return this;
            }

            /**
             * <p>Indicates whether logging is enabled.</p>
             * <ul>
             * <li><p><code>true</code>: Enabled.</p>
             * </li>
             * <li><p><code>false</code>: Disabled.</p>
             * </li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>true</p>
             */
            public Builder enableLog(Boolean enableLog) {
                this.enableLog = enableLog;
                return this;
            }

            /**
             * <p>The number of executors.</p>
             * 
             * <strong>example:</strong>
             * <p>2</p>
             */
            public Builder executorNum(Long executorNum) {
                this.executorNum = executorNum;
                return this;
            }

            /**
             * <p>The primary key ID.</p>
             * 
             * <strong>example:</strong>
             * <p>3402</p>
             */
            public Builder id(Long id) {
                this.id = id;
                return this;
            }

            /**
             * <p>The number of jobs.</p>
             * 
             * <strong>example:</strong>
             * <p>100</p>
             */
            public Builder jobNum(Integer jobNum) {
                this.jobNum = jobNum;
                return this;
            }

            /**
             * LabelRouteStrategy.
             */
            public Builder labelRouteStrategy(Integer labelRouteStrategy) {
                this.labelRouteStrategy = labelRouteStrategy;
                return this;
            }

            /**
             * <p>The leader address.</p>
             * 
             * <strong>example:</strong>
             * <p><a href="http://28.***.***.3:80">http://28.***.***.3:80</a></p>
             */
            public Builder leader(String leader) {
                this.leader = leader;
                return this;
            }

            /**
             * <p>The maximum concurrency.</p>
             * 
             * <strong>example:</strong>
             * <p>100</p>
             */
            public Builder maxConcurrency(Integer maxConcurrency) {
                this.maxConcurrency = maxConcurrency;
                return this;
            }

            /**
             * <p>The maximum number of jobs.</p>
             * 
             * <strong>example:</strong>
             * <p>1000</p>
             */
            public Builder maxJobs(Integer maxJobs) {
                this.maxJobs = maxJobs;
                return this;
            }

            /**
             * <p>The title of the application.</p>
             * 
             * <strong>example:</strong>
             * <p>测试应用</p>
             */
            public Builder title(String title) {
                this.title = title;
                return this;
            }

            /**
             * <p>The last user to update the application.</p>
             * 
             * <strong>example:</strong>
             * <p>18582193685027xx</p>
             */
            public Builder updater(String updater) {
                this.updater = updater;
                return this;
            }

            public Data build() {
                return new Data(this);
            } 

        } 

    }
}
