// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sophonsoar20250903.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link UpdatePlaybookResponseBody} extends {@link TeaModel}
 *
 * <p>UpdatePlaybookResponseBody</p>
 */
public class UpdatePlaybookResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("PlaybookUuid")
    private String playbookUuid;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    private UpdatePlaybookResponseBody(Builder builder) {
        this.playbookUuid = builder.playbookUuid;
        this.requestId = builder.requestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static UpdatePlaybookResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return playbookUuid
     */
    public String getPlaybookUuid() {
        return this.playbookUuid;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    public static final class Builder {
        private String playbookUuid; 
        private String requestId; 

        private Builder() {
        } 

        private Builder(UpdatePlaybookResponseBody model) {
            this.playbookUuid = model.playbookUuid;
            this.requestId = model.requestId;
        } 

        /**
         * <p>UUID of the playbook.</p>
         * 
         * <strong>example:</strong>
         * <p>8f55e76d-b5d5-4720-9cd7-xxxxx</p>
         */
        public Builder playbookUuid(String playbookUuid) {
            this.playbookUuid = playbookUuid;
            return this;
        }

        /**
         * <p>The ID of this request, which is a unique identifier generated by Alibaba Cloud for the request, and can be used for troubleshooting and problem localization.</p>
         * 
         * <strong>example:</strong>
         * <p>1A01B0BA-<strong><strong>-5813-</strong></strong>-A5DA15FA95AE</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        public UpdatePlaybookResponseBody build() {
            return new UpdatePlaybookResponseBody(this);
        } 

    } 

}
