// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sddp20190103.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link DescribeDataObjectsResponseBody} extends {@link TeaModel}
 *
 * <p>DescribeDataObjectsResponseBody</p>
 */
public class DescribeDataObjectsResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("CurrentPage")
    private Integer currentPage;

    @com.aliyun.core.annotation.NameInMap("Items")
    private java.util.List<Items> items;

    @com.aliyun.core.annotation.NameInMap("PageSize")
    private Integer pageSize;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    @com.aliyun.core.annotation.NameInMap("TotalCount")
    private Integer totalCount;

    private DescribeDataObjectsResponseBody(Builder builder) {
        this.currentPage = builder.currentPage;
        this.items = builder.items;
        this.pageSize = builder.pageSize;
        this.requestId = builder.requestId;
        this.totalCount = builder.totalCount;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static DescribeDataObjectsResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return currentPage
     */
    public Integer getCurrentPage() {
        return this.currentPage;
    }

    /**
     * @return items
     */
    public java.util.List<Items> getItems() {
        return this.items;
    }

    /**
     * @return pageSize
     */
    public Integer getPageSize() {
        return this.pageSize;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * @return totalCount
     */
    public Integer getTotalCount() {
        return this.totalCount;
    }

    public static final class Builder {
        private Integer currentPage; 
        private java.util.List<Items> items; 
        private Integer pageSize; 
        private String requestId; 
        private Integer totalCount; 

        private Builder() {
        } 

        private Builder(DescribeDataObjectsResponseBody model) {
            this.currentPage = model.currentPage;
            this.items = model.items;
            this.pageSize = model.pageSize;
            this.requestId = model.requestId;
            this.totalCount = model.totalCount;
        } 

        /**
         * <p>When performing a paginated query, set the current page number. Default value: <strong>1</strong>.</p>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        public Builder currentPage(Integer currentPage) {
            this.currentPage = currentPage;
            return this;
        }

        /**
         * <p>List of data objects.</p>
         */
        public Builder items(java.util.List<Items> items) {
            this.items = items;
            return this;
        }

        /**
         * <p>When performing a paginated query, this sets the maximum number of data asset instances to display per page. Default value: <strong>10</strong>.</p>
         * 
         * <strong>example:</strong>
         * <p>10</p>
         */
        public Builder pageSize(Integer pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /**
         * <p>The ID of this call request is a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and locate issues.</p>
         * 
         * <strong>example:</strong>
         * <p>E6F6460E-4330-549A-BD89-C183FB17571E</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * <p>The total number of query results.</p>
         * 
         * <strong>example:</strong>
         * <p>21</p>
         */
        public Builder totalCount(Integer totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        public DescribeDataObjectsResponseBody build() {
            return new DescribeDataObjectsResponseBody(this);
        } 

    } 

    /**
     * 
     * {@link DescribeDataObjectsResponseBody} extends {@link TeaModel}
     *
     * <p>DescribeDataObjectsResponseBody</p>
     */
    public static class ModelTags extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("Id")
        private Long id;

        @com.aliyun.core.annotation.NameInMap("Name")
        private String name;

        private ModelTags(Builder builder) {
            this.id = builder.id;
            this.name = builder.name;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static ModelTags create() {
            return builder().build();
        }

        /**
         * @return id
         */
        public Long getId() {
            return this.id;
        }

        /**
         * @return name
         */
        public String getName() {
            return this.name;
        }

        public static final class Builder {
            private Long id; 
            private String name; 

            private Builder() {
            } 

            private Builder(ModelTags model) {
                this.id = model.id;
                this.name = model.name;
            } 

            /**
             * <p>Data tag ID. Values:</p>
             * <ul>
             * <li><strong>101</strong>: Personal sensitive information.</li>
             * <li><strong>102</strong>: Personal information.</li>
             * <li><strong>107</strong>: General information.</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>101</p>
             */
            public Builder id(Long id) {
                this.id = id;
                return this;
            }

            /**
             * <p>Data tag name. Values:</p>
             * <ul>
             * <li><strong>Personal sensitive information.</strong></li>
             * <li><strong>Personal information.</strong></li>
             * <li><strong>General information.</strong></li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>Personal sensitive information</p>
             */
            public Builder name(String name) {
                this.name = name;
                return this;
            }

            public ModelTags build() {
                return new ModelTags(this);
            } 

        } 

    }
    /**
     * 
     * {@link DescribeDataObjectsResponseBody} extends {@link TeaModel}
     *
     * <p>DescribeDataObjectsResponseBody</p>
     */
    public static class RuleList extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("RiskLevelId")
        private Long riskLevelId;

        @com.aliyun.core.annotation.NameInMap("RiskLevelName")
        private String riskLevelName;

        @com.aliyun.core.annotation.NameInMap("RuleCount")
        private Integer ruleCount;

        @com.aliyun.core.annotation.NameInMap("RuleId")
        private Long ruleId;

        @com.aliyun.core.annotation.NameInMap("RuleName")
        private String ruleName;

        private RuleList(Builder builder) {
            this.riskLevelId = builder.riskLevelId;
            this.riskLevelName = builder.riskLevelName;
            this.ruleCount = builder.ruleCount;
            this.ruleId = builder.ruleId;
            this.ruleName = builder.ruleName;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static RuleList create() {
            return builder().build();
        }

        /**
         * @return riskLevelId
         */
        public Long getRiskLevelId() {
            return this.riskLevelId;
        }

        /**
         * @return riskLevelName
         */
        public String getRiskLevelName() {
            return this.riskLevelName;
        }

        /**
         * @return ruleCount
         */
        public Integer getRuleCount() {
            return this.ruleCount;
        }

        /**
         * @return ruleId
         */
        public Long getRuleId() {
            return this.ruleId;
        }

        /**
         * @return ruleName
         */
        public String getRuleName() {
            return this.ruleName;
        }

        public static final class Builder {
            private Long riskLevelId; 
            private String riskLevelName; 
            private Integer ruleCount; 
            private Long ruleId; 
            private String ruleName; 

            private Builder() {
            } 

            private Builder(RuleList model) {
                this.riskLevelId = model.riskLevelId;
                this.riskLevelName = model.riskLevelName;
                this.ruleCount = model.ruleCount;
                this.ruleId = model.ruleId;
                this.ruleName = model.ruleName;
            } 

            /**
             * <p>Risk level ID for sensitive data identification rules. Values:</p>
             * <ul>
             * <li><strong>1</strong>: N/A: No sensitive data identified.</li>
             * <li><strong>2</strong>: S1: Level 1 sensitive data.</li>
             * <li><strong>3</strong>: S2: Level 2 sensitive data.</li>
             * <li><strong>4</strong>: S3: Level 3 sensitive data.</li>
             * <li><strong>5</strong>: S4: Level 4 sensitive data.</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>2</p>
             */
            public Builder riskLevelId(Long riskLevelId) {
                this.riskLevelId = riskLevelId;
                return this;
            }

            /**
             * <p>Risk level name for the data asset table. Values:</p>
             * <ul>
             * <li><strong>N/A</strong>: No sensitive data identified.</li>
             * <li><strong>S1</strong>: Level 1 sensitive data.</li>
             * <li><strong>S2</strong>: Level 2 sensitive data.</li>
             * <li><strong>S3</strong>: Level 3 sensitive data.</li>
             * <li><strong>S4</strong>: Level 4 sensitive data.</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>S1</p>
             */
            public Builder riskLevelName(String riskLevelName) {
                this.riskLevelName = riskLevelName;
                return this;
            }

            /**
             * <p>Number of matched identification models.</p>
             * 
             * <strong>example:</strong>
             * <p>590</p>
             */
            public Builder ruleCount(Integer ruleCount) {
                this.ruleCount = ruleCount;
                return this;
            }

            /**
             * <p>Identification model ID.</p>
             * 
             * <strong>example:</strong>
             * <p>1080</p>
             */
            public Builder ruleId(Long ruleId) {
                this.ruleId = ruleId;
                return this;
            }

            /**
             * <p>Identification model name.</p>
             * 
             * <strong>example:</strong>
             * <p>name</p>
             */
            public Builder ruleName(String ruleName) {
                this.ruleName = ruleName;
                return this;
            }

            public RuleList build() {
                return new RuleList(this);
            } 

        } 

    }
    /**
     * 
     * {@link DescribeDataObjectsResponseBody} extends {@link TeaModel}
     *
     * <p>DescribeDataObjectsResponseBody</p>
     */
    public static class Items extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("Categories")
        private java.util.List<String> categories;

        @com.aliyun.core.annotation.NameInMap("Id")
        private String id;

        @com.aliyun.core.annotation.NameInMap("InstanceDescription")
        private String instanceDescription;

        @com.aliyun.core.annotation.NameInMap("InstanceId")
        private String instanceId;

        @com.aliyun.core.annotation.NameInMap("LastModifiedTime")
        private Long lastModifiedTime;

        @com.aliyun.core.annotation.NameInMap("LastScanTime")
        private Long lastScanTime;

        @com.aliyun.core.annotation.NameInMap("MemberAccount")
        private Long memberAccount;

        @com.aliyun.core.annotation.NameInMap("ModelTags")
        private java.util.List<ModelTags> modelTags;

        @com.aliyun.core.annotation.NameInMap("Name")
        private String name;

        @com.aliyun.core.annotation.NameInMap("ObjectFileCategory")
        private String objectFileCategory;

        @com.aliyun.core.annotation.NameInMap("ObjectType")
        private String objectType;

        @com.aliyun.core.annotation.NameInMap("Path")
        private String path;

        @com.aliyun.core.annotation.NameInMap("ProductCode")
        private String productCode;

        @com.aliyun.core.annotation.NameInMap("ProductId")
        private Long productId;

        @com.aliyun.core.annotation.NameInMap("RegionId")
        private String regionId;

        @com.aliyun.core.annotation.NameInMap("RegionName")
        private String regionName;

        @com.aliyun.core.annotation.NameInMap("RuleList")
        private java.util.List<RuleList> ruleList;

        @com.aliyun.core.annotation.NameInMap("SensitiveCount")
        private Integer sensitiveCount;

        @com.aliyun.core.annotation.NameInMap("TemplateId")
        private Long templateId;

        private Items(Builder builder) {
            this.categories = builder.categories;
            this.id = builder.id;
            this.instanceDescription = builder.instanceDescription;
            this.instanceId = builder.instanceId;
            this.lastModifiedTime = builder.lastModifiedTime;
            this.lastScanTime = builder.lastScanTime;
            this.memberAccount = builder.memberAccount;
            this.modelTags = builder.modelTags;
            this.name = builder.name;
            this.objectFileCategory = builder.objectFileCategory;
            this.objectType = builder.objectType;
            this.path = builder.path;
            this.productCode = builder.productCode;
            this.productId = builder.productId;
            this.regionId = builder.regionId;
            this.regionName = builder.regionName;
            this.ruleList = builder.ruleList;
            this.sensitiveCount = builder.sensitiveCount;
            this.templateId = builder.templateId;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static Items create() {
            return builder().build();
        }

        /**
         * @return categories
         */
        public java.util.List<String> getCategories() {
            return this.categories;
        }

        /**
         * @return id
         */
        public String getId() {
            return this.id;
        }

        /**
         * @return instanceDescription
         */
        public String getInstanceDescription() {
            return this.instanceDescription;
        }

        /**
         * @return instanceId
         */
        public String getInstanceId() {
            return this.instanceId;
        }

        /**
         * @return lastModifiedTime
         */
        public Long getLastModifiedTime() {
            return this.lastModifiedTime;
        }

        /**
         * @return lastScanTime
         */
        public Long getLastScanTime() {
            return this.lastScanTime;
        }

        /**
         * @return memberAccount
         */
        public Long getMemberAccount() {
            return this.memberAccount;
        }

        /**
         * @return modelTags
         */
        public java.util.List<ModelTags> getModelTags() {
            return this.modelTags;
        }

        /**
         * @return name
         */
        public String getName() {
            return this.name;
        }

        /**
         * @return objectFileCategory
         */
        public String getObjectFileCategory() {
            return this.objectFileCategory;
        }

        /**
         * @return objectType
         */
        public String getObjectType() {
            return this.objectType;
        }

        /**
         * @return path
         */
        public String getPath() {
            return this.path;
        }

        /**
         * @return productCode
         */
        public String getProductCode() {
            return this.productCode;
        }

        /**
         * @return productId
         */
        public Long getProductId() {
            return this.productId;
        }

        /**
         * @return regionId
         */
        public String getRegionId() {
            return this.regionId;
        }

        /**
         * @return regionName
         */
        public String getRegionName() {
            return this.regionName;
        }

        /**
         * @return ruleList
         */
        public java.util.List<RuleList> getRuleList() {
            return this.ruleList;
        }

        /**
         * @return sensitiveCount
         */
        public Integer getSensitiveCount() {
            return this.sensitiveCount;
        }

        /**
         * @return templateId
         */
        public Long getTemplateId() {
            return this.templateId;
        }

        public static final class Builder {
            private java.util.List<String> categories; 
            private String id; 
            private String instanceDescription; 
            private String instanceId; 
            private Long lastModifiedTime; 
            private Long lastScanTime; 
            private Long memberAccount; 
            private java.util.List<ModelTags> modelTags; 
            private String name; 
            private String objectFileCategory; 
            private String objectType; 
            private String path; 
            private String productCode; 
            private Long productId; 
            private String regionId; 
            private String regionName; 
            private java.util.List<RuleList> ruleList; 
            private Integer sensitiveCount; 
            private Long templateId; 

            private Builder() {
            } 

            private Builder(Items model) {
                this.categories = model.categories;
                this.id = model.id;
                this.instanceDescription = model.instanceDescription;
                this.instanceId = model.instanceId;
                this.lastModifiedTime = model.lastModifiedTime;
                this.lastScanTime = model.lastScanTime;
                this.memberAccount = model.memberAccount;
                this.modelTags = model.modelTags;
                this.name = model.name;
                this.objectFileCategory = model.objectFileCategory;
                this.objectType = model.objectType;
                this.path = model.path;
                this.productCode = model.productCode;
                this.productId = model.productId;
                this.regionId = model.regionId;
                this.regionName = model.regionName;
                this.ruleList = model.ruleList;
                this.sensitiveCount = model.sensitiveCount;
                this.templateId = model.templateId;
            } 

            /**
             * <p>List of industry categories for the sensitive data.</p>
             */
            public Builder categories(java.util.List<String> categories) {
                this.categories = categories;
                return this;
            }

            /**
             * <p>The unique identifier ID of the data object.</p>
             * 
             * <strong>example:</strong>
             * <p>20000</p>
             */
            public Builder id(String id) {
                this.id = id;
                return this;
            }

            /**
             * <p>The instance description of the data object.</p>
             * 
             * <strong>example:</strong>
             * <p>instance description</p>
             */
            public Builder instanceDescription(String instanceDescription) {
                this.instanceDescription = instanceDescription;
                return this;
            }

            /**
             * <p>Data asset instance ID.</p>
             * 
             * <strong>example:</strong>
             * <p>rm-12*****</p>
             */
            public Builder instanceId(String instanceId) {
                this.instanceId = instanceId;
                return this;
            }

            /**
             * <p>Latest file modification time, in milliseconds.</p>
             * 
             * <strong>example:</strong>
             * <p>1687676649830</p>
             */
            public Builder lastModifiedTime(Long lastModifiedTime) {
                this.lastModifiedTime = lastModifiedTime;
                return this;
            }

            /**
             * <p>The timestamp of the last scan, in milliseconds.</p>
             * 
             * <strong>example:</strong>
             * <p>1687676649830</p>
             */
            public Builder lastScanTime(Long lastScanTime) {
                this.lastScanTime = lastScanTime;
                return this;
            }

            /**
             * <p>Member account ID.</p>
             * 
             * <strong>example:</strong>
             * <p>**********8103</p>
             */
            public Builder memberAccount(Long memberAccount) {
                this.memberAccount = memberAccount;
                return this;
            }

            /**
             * <p>List of data tags.</p>
             */
            public Builder modelTags(java.util.List<ModelTags> modelTags) {
                this.modelTags = modelTags;
                return this;
            }

            /**
             * <p>The name of the data object.</p>
             * 
             * <strong>example:</strong>
             * <p>t_sddp_selfmysql_pers0</p>
             */
            public Builder name(String name) {
                this.name = name;
                return this;
            }

            /**
             * <p>File category name.</p>
             * 
             * <strong>example:</strong>
             * <p>text file</p>
             */
            public Builder objectFileCategory(String objectFileCategory) {
                this.objectFileCategory = objectFileCategory;
                return this;
            }

            /**
             * <p>The type of the data object.</p>
             * 
             * <strong>example:</strong>
             * <p>text type</p>
             */
            public Builder objectType(String objectType) {
                this.objectType = objectType;
                return this;
            }

            /**
             * <p>The path of the data object.</p>
             * 
             * <strong>example:</strong>
             * <p>rm-12**.db_***</p>
             */
            public Builder path(String path) {
                this.path = path;
                return this;
            }

            /**
             * <p>The product name that the data object belongs to. Values:</p>
             * <ul>
             * <li><strong>MaxCompute</strong></li>
             * <li><strong>OSS</strong></li>
             * <li><strong>ADB-MYSQL</strong></li>
             * <li><strong>TableStore</strong></li>
             * <li><strong>RDS</strong></li>
             * <li><strong>SELF_DB</strong></li>
             * <li><strong>PolarDB-X</strong></li>
             * <li><strong>PolarDB</strong></li>
             * <li><strong>ADB-PG</strong></li>
             * <li><strong>OceanBase</strong></li>
             * <li><strong>MongoDB</strong></li>
             * <li><strong>Redis</strong></li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>RDS</p>
             */
            public Builder productCode(String productCode) {
                this.productCode = productCode;
                return this;
            }

            /**
             * <p>The ID corresponding to the product name that the data object belongs to. Values:</p>
             * <ul>
             * <li><strong>1</strong>: MaxCompute</li>
             * <li><strong>2</strong>: OSS</li>
             * <li><strong>3</strong>: ADB-MYSQL</li>
             * <li><strong>4</strong>: TableStore</li>
             * <li><strong>5</strong>: RDS</li>
             * <li><strong>6</strong>: SELF_DB</li>
             * <li><strong>7</strong>: PolarDB-X</li>
             * <li><strong>8</strong>: PolarDB</li>
             * <li><strong>9</strong>: ADB-PG</li>
             * <li><strong>10</strong>: OceanBase</li>
             * <li><strong>11</strong>: MongoDB</li>
             * <li><strong>25</strong>: Redis</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>5</p>
             */
            public Builder productId(Long productId) {
                this.productId = productId;
                return this;
            }

            /**
             * <p>The region ID to which the OSS storage object belongs.</p>
             * 
             * <strong>example:</strong>
             * <p>cn-hangzhou</p>
             */
            public Builder regionId(String regionId) {
                this.regionId = regionId;
                return this;
            }

            /**
             * <p>Region name.</p>
             * 
             * <strong>example:</strong>
             * <p>cn-hangzhou</p>
             */
            public Builder regionName(String regionName) {
                this.regionName = regionName;
                return this;
            }

            /**
             * <p>List of matched identification models.</p>
             */
            public Builder ruleList(java.util.List<RuleList> ruleList) {
                this.ruleList = ruleList;
                return this;
            }

            /**
             * <p>Number of sensitive data items.</p>
             * 
             * <strong>example:</strong>
             * <p>1</p>
             */
            public Builder sensitiveCount(Integer sensitiveCount) {
                this.sensitiveCount = sensitiveCount;
                return this;
            }

            /**
             * <p>Industry template ID</p>
             * 
             * <strong>example:</strong>
             * <p>1</p>
             */
            public Builder templateId(Long templateId) {
                this.templateId = templateId;
                return this;
            }

            public Items build() {
                return new Items(this);
            } 

        } 

    }
}
