// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.agency20221216.models;

import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * {@link GetAccountInfoResponseBody} extends {@link TeaModel}
 *
 * <p>GetAccountInfoResponseBody</p>
 */
public class GetAccountInfoResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("AccountInfoList")
    private AccountInfoList accountInfoList;

    @com.aliyun.core.annotation.NameInMap("Code")
    private String code;

    @com.aliyun.core.annotation.NameInMap("Message")
    private String message;

    @com.aliyun.core.annotation.NameInMap("PageInfo")
    private PageInfo pageInfo;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    @com.aliyun.core.annotation.NameInMap("Success")
    private Boolean success;

    private GetAccountInfoResponseBody(Builder builder) {
        this.accountInfoList = builder.accountInfoList;
        this.code = builder.code;
        this.message = builder.message;
        this.pageInfo = builder.pageInfo;
        this.requestId = builder.requestId;
        this.success = builder.success;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static GetAccountInfoResponseBody create() {
        return builder().build();
    }

    /**
     * @return accountInfoList
     */
    public AccountInfoList getAccountInfoList() {
        return this.accountInfoList;
    }

    /**
     * @return code
     */
    public String getCode() {
        return this.code;
    }

    /**
     * @return message
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * @return pageInfo
     */
    public PageInfo getPageInfo() {
        return this.pageInfo;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * @return success
     */
    public Boolean getSuccess() {
        return this.success;
    }

    public static final class Builder {
        private AccountInfoList accountInfoList; 
        private String code; 
        private String message; 
        private PageInfo pageInfo; 
        private String requestId; 
        private Boolean success; 

        /**
         * Account Type:
         * <p>
         * - 1 Agency\"s End User
         * - 2 Reseller\"s End User
         * - 3 Enterprise
         * - 4 T2 Agency Partner
         * - 5 T2 Reseller Partner
         * - 6 T2 Agency+Reseller Partner
         */
        public Builder accountInfoList(AccountInfoList accountInfoList) {
            this.accountInfoList = accountInfoList;
            return this;
        }

        /**
         * Candidate Value: True/False, which indicates whether the current API call itself is successful. It does not guarantee the success of subsequent business operations.
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * message
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Pagination, page volume in total.
         */
        public Builder pageInfo(PageInfo pageInfo) {
            this.pageInfo = pageInfo;
            return this;
        }

        /**
         * Request id, a unique identifier generated by Alibaba cloud for the request.
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Pagination, record number on each page.
         */
        public Builder success(Boolean success) {
            this.success = success;
            return this;
        }

        public GetAccountInfoResponseBody build() {
            return new GetAccountInfoResponseBody(this);
        } 

    } 

    public static class AccountInfo extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("AccountNickname")
        private String accountNickname;

        @com.aliyun.core.annotation.NameInMap("AliyunId")
        private String aliyunId;

        @com.aliyun.core.annotation.NameInMap("AssociationSuccessTime")
        private String associationSuccessTime;

        @com.aliyun.core.annotation.NameInMap("Cid")
        private Long cid;

        @com.aliyun.core.annotation.NameInMap("CustomerBd")
        private String customerBd;

        @com.aliyun.core.annotation.NameInMap("DelayAmount")
        private String delayAmount;

        @com.aliyun.core.annotation.NameInMap("DelayStatus")
        private String delayStatus;

        @com.aliyun.core.annotation.NameInMap("Email")
        private String email;

        @com.aliyun.core.annotation.NameInMap("Mobile")
        private String mobile;

        @com.aliyun.core.annotation.NameInMap("NewBuyStatus")
        private String newBuyStatus;

        @com.aliyun.core.annotation.NameInMap("Remark")
        private String remark;

        @com.aliyun.core.annotation.NameInMap("SubAccountType")
        private Integer subAccountType;

        @com.aliyun.core.annotation.NameInMap("Uid")
        private Long uid;

        private AccountInfo(Builder builder) {
            this.accountNickname = builder.accountNickname;
            this.aliyunId = builder.aliyunId;
            this.associationSuccessTime = builder.associationSuccessTime;
            this.cid = builder.cid;
            this.customerBd = builder.customerBd;
            this.delayAmount = builder.delayAmount;
            this.delayStatus = builder.delayStatus;
            this.email = builder.email;
            this.mobile = builder.mobile;
            this.newBuyStatus = builder.newBuyStatus;
            this.remark = builder.remark;
            this.subAccountType = builder.subAccountType;
            this.uid = builder.uid;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static AccountInfo create() {
            return builder().build();
        }

        /**
         * @return accountNickname
         */
        public String getAccountNickname() {
            return this.accountNickname;
        }

        /**
         * @return aliyunId
         */
        public String getAliyunId() {
            return this.aliyunId;
        }

        /**
         * @return associationSuccessTime
         */
        public String getAssociationSuccessTime() {
            return this.associationSuccessTime;
        }

        /**
         * @return cid
         */
        public Long getCid() {
            return this.cid;
        }

        /**
         * @return customerBd
         */
        public String getCustomerBd() {
            return this.customerBd;
        }

        /**
         * @return delayAmount
         */
        public String getDelayAmount() {
            return this.delayAmount;
        }

        /**
         * @return delayStatus
         */
        public String getDelayStatus() {
            return this.delayStatus;
        }

        /**
         * @return email
         */
        public String getEmail() {
            return this.email;
        }

        /**
         * @return mobile
         */
        public String getMobile() {
            return this.mobile;
        }

        /**
         * @return newBuyStatus
         */
        public String getNewBuyStatus() {
            return this.newBuyStatus;
        }

        /**
         * @return remark
         */
        public String getRemark() {
            return this.remark;
        }

        /**
         * @return subAccountType
         */
        public Integer getSubAccountType() {
            return this.subAccountType;
        }

        /**
         * @return uid
         */
        public Long getUid() {
            return this.uid;
        }

        public static final class Builder {
            private String accountNickname; 
            private String aliyunId; 
            private String associationSuccessTime; 
            private Long cid; 
            private String customerBd; 
            private String delayAmount; 
            private String delayStatus; 
            private String email; 
            private String mobile; 
            private String newBuyStatus; 
            private String remark; 
            private Integer subAccountType; 
            private Long uid; 

            /**
             * The E-mail of Distribution Customer.
             */
            public Builder accountNickname(String accountNickname) {
                this.accountNickname = accountNickname;
                return this;
            }

            /**
             * Account CID of Distribution Customer.
             */
            public Builder aliyunId(String aliyunId) {
                this.aliyunId = aliyunId;
                return this;
            }

            /**
             * XXX Technology LTD.
             */
            public Builder associationSuccessTime(String associationSuccessTime) {
                this.associationSuccessTime = associationSuccessTime;
                return this;
            }

            /**
             * customer\"s CID
             */
            public Builder cid(Long cid) {
                this.cid = cid;
                return this;
            }

            /**
             * customer manager
             */
            public Builder customerBd(String customerBd) {
                this.customerBd = customerBd;
                return this;
            }

            /**
             * The account have Shutdown-delay Privilege, After Shutdown-delay Credit is ran out, Alibaba Cloud will take over resources and keep the instance for 15 days. In addition, the instance will be released if Sub Account failed to pay the bill within these 15 days.
             */
            public Builder delayAmount(String delayAmount) {
                this.delayAmount = delayAmount;
                return this;
            }

            /**
             * Partner\"s Shutdown Policy Management for Sub Account.
             * <p>
             * 1: delayStop. The account have Shutdown-delay Privilege, After Shutdown-delay Credit is ran out, Alibaba Cloud will take over resources and keep the instance for 15 days. In addition, the instance will be released if Sub Account failed to pay the bill within these 15 days.
             * 2: noStop. Partner will manually manage Shutdown Status for Sub Account. Meanwhile, System would not manage the resource\"s life-circle of Sub Account.
             * 3: immediatelyStop. Once valid quota of Sub Account falls below 0 and be identified as defaulting account, it will trigger the instance shutdown immediately.
             */
            public Builder delayStatus(String delayStatus) {
                this.delayStatus = delayStatus;
                return this;
            }

            /**
             * Sub Account
             */
            public Builder email(String email) {
                this.email = email;
                return this;
            }

            /**
             * Account UID of Distribution Customer.
             */
            public Builder mobile(String mobile) {
                this.mobile = mobile;
                return this;
            }

            /**
             * Purchase Forbidden：Ban the new purchase action
             * <p>
             * normal：Normal--End Use can issue Cloud Resource order immediately.
             */
            public Builder newBuyStatus(String newBuyStatus) {
                this.newBuyStatus = newBuyStatus;
                return this;
            }

            /**
             * Valid mobile number of Distribution Customer.
             */
            public Builder remark(String remark) {
                this.remark = remark;
                return this;
            }

            /**
             * The name of Sub Account:
             * <p>
             * 1.	Use the official name of Company, if Sub Account is an enterprise.
             * 2.	Use the official name of Partner, if Sub Account is a T2 reseller.
             */
            public Builder subAccountType(Integer subAccountType) {
                this.subAccountType = subAccountType;
                return this;
            }

            /**
             * Request ID, the unique request identifier generated by Alibaba Cloud.
             */
            public Builder uid(Long uid) {
                this.uid = uid;
                return this;
            }

            public AccountInfo build() {
                return new AccountInfo(this);
            } 

        } 

    }
    public static class AccountInfoList extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("AccountInfo")
        private java.util.List < AccountInfo> accountInfo;

        private AccountInfoList(Builder builder) {
            this.accountInfo = builder.accountInfo;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static AccountInfoList create() {
            return builder().build();
        }

        /**
         * @return accountInfo
         */
        public java.util.List < AccountInfo> getAccountInfo() {
            return this.accountInfo;
        }

        public static final class Builder {
            private java.util.List < AccountInfo> accountInfo; 

            /**
             * AccountInfo.
             */
            public Builder accountInfo(java.util.List < AccountInfo> accountInfo) {
                this.accountInfo = accountInfo;
                return this;
            }

            public AccountInfoList build() {
                return new AccountInfoList(this);
            } 

        } 

    }
    public static class PageInfo extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("Page")
        private Integer page;

        @com.aliyun.core.annotation.NameInMap("PageSize")
        private Integer pageSize;

        @com.aliyun.core.annotation.NameInMap("Total")
        private Integer total;

        private PageInfo(Builder builder) {
            this.page = builder.page;
            this.pageSize = builder.pageSize;
            this.total = builder.total;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static PageInfo create() {
            return builder().build();
        }

        /**
         * @return page
         */
        public Integer getPage() {
            return this.page;
        }

        /**
         * @return pageSize
         */
        public Integer getPageSize() {
            return this.pageSize;
        }

        /**
         * @return total
         */
        public Integer getTotal() {
            return this.total;
        }

        public static final class Builder {
            private Integer page; 
            private Integer pageSize; 
            private Integer total; 

            /**
             * Account Information
             */
            public Builder page(Integer page) {
                this.page = page;
                return this;
            }

            /**
             * Pagination, current page.
             */
            public Builder pageSize(Integer pageSize) {
                this.pageSize = pageSize;
                return this;
            }

            /**
             * List of Account Information
             */
            public Builder total(Integer total) {
                this.total = total;
                return this;
            }

            public PageInfo build() {
                return new PageInfo(this);
            } 

        } 

    }
}
