// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.dysmsapi20170525.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link CreateSmsSignResponseBody} extends {@link TeaModel}
 *
 * <p>CreateSmsSignResponseBody</p>
 */
public class CreateSmsSignResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("Code")
    private String code;

    @com.aliyun.core.annotation.NameInMap("Message")
    private String message;

    @com.aliyun.core.annotation.NameInMap("OrderId")
    private String orderId;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    @com.aliyun.core.annotation.NameInMap("SignName")
    private String signName;

    private CreateSmsSignResponseBody(Builder builder) {
        this.code = builder.code;
        this.message = builder.message;
        this.orderId = builder.orderId;
        this.requestId = builder.requestId;
        this.signName = builder.signName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static CreateSmsSignResponseBody create() {
        return builder().build();
    }

    /**
     * @return code
     */
    public String getCode() {
        return this.code;
    }

    /**
     * @return message
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * @return orderId
     */
    public String getOrderId() {
        return this.orderId;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * @return signName
     */
    public String getSignName() {
        return this.signName;
    }

    public static final class Builder {
        private String code; 
        private String message; 
        private String orderId; 
        private String requestId; 
        private String signName; 

        /**
         * <p>Request status code.</p>
         * <ul>
         * <li>OK indicates a successful request.</li>
         * <li>For other error codes, refer to the <a href="https://help.aliyun.com/document_detail/101346.html">Error Code List</a>.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>OK</p>
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * <p>Description of the status code.</p>
         * 
         * <strong>example:</strong>
         * <p>successful</p>
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * <p>Work order number.</p>
         * <p>This parameter is used by auditors when querying the audit. You will need to provide this work order number if you require expedited review.</p>
         * 
         * <strong>example:</strong>
         * <p>2004415****</p>
         */
        public Builder orderId(String orderId) {
            this.orderId = orderId;
            return this;
        }

        /**
         * <p>The ID of this call request, which is a unique identifier generated by Alibaba Cloud for the request and can be used for troubleshooting and issue localization.</p>
         * 
         * <strong>example:</strong>
         * <p>CCA2BCFF-2BA7-427C-90EE-AC6994748607</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * <p>Signature name.</p>
         * 
         * <strong>example:</strong>
         * <p>Aliyun</p>
         */
        public Builder signName(String signName) {
            this.signName = signName;
            return this;
        }

        public CreateSmsSignResponseBody build() {
            return new CreateSmsSignResponseBody(this);
        } 

    } 

}
