// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link DescribeCanAccessVpcSaleResponseBody} extends {@link TeaModel}
 *
 * <p>DescribeCanAccessVpcSaleResponseBody</p>
 */
public class DescribeCanAccessVpcSaleResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("CanAccess")
    private Boolean canAccess;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    private DescribeCanAccessVpcSaleResponseBody(Builder builder) {
        this.canAccess = builder.canAccess;
        this.requestId = builder.requestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static DescribeCanAccessVpcSaleResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return canAccess
     */
    public Boolean getCanAccess() {
        return this.canAccess;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    public static final class Builder {
        private Boolean canAccess; 
        private String requestId; 

        private Builder() {
        } 

        private Builder(DescribeCanAccessVpcSaleResponseBody model) {
            this.canAccess = model.canAccess;
            this.requestId = model.requestId;
        } 

        /**
         * <p>Indicates whether the purchase can be made according to VPC.</p>
         * 
         * <strong>example:</strong>
         * <p>true</p>
         */
        public Builder canAccess(Boolean canAccess) {
            this.canAccess = canAccess;
            return this;
        }

        /**
         * <p>The ID of this call request, a unique identifier generated by Alibaba Cloud for this request, which can be used for troubleshooting and problem localization.</p>
         * 
         * <strong>example:</strong>
         * <p>7BC55C8F-226E-5AF5-9A2C-2EC43864****</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        public DescribeCanAccessVpcSaleResponseBody build() {
            return new DescribeCanAccessVpcSaleResponseBody(this);
        } 

    } 

}
