// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link DescribeBackupPolicyResponseBody} extends {@link TeaModel}
 *
 * <p>DescribeBackupPolicyResponseBody</p>
 */
public class DescribeBackupPolicyResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("BackupPolicyDetail")
    private BackupPolicyDetail backupPolicyDetail;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    private DescribeBackupPolicyResponseBody(Builder builder) {
        this.backupPolicyDetail = builder.backupPolicyDetail;
        this.requestId = builder.requestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static DescribeBackupPolicyResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return backupPolicyDetail
     */
    public BackupPolicyDetail getBackupPolicyDetail() {
        return this.backupPolicyDetail;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    public static final class Builder {
        private BackupPolicyDetail backupPolicyDetail; 
        private String requestId; 

        private Builder() {
        } 

        private Builder(DescribeBackupPolicyResponseBody model) {
            this.backupPolicyDetail = model.backupPolicyDetail;
            this.requestId = model.requestId;
        } 

        /**
         * <p>The details of the policy.</p>
         */
        public Builder backupPolicyDetail(BackupPolicyDetail backupPolicyDetail) {
            this.backupPolicyDetail = backupPolicyDetail;
            return this;
        }

        /**
         * <p>The request ID. It is a unique identifier generated by Alibaba Cloud for the request and can be used for troubleshooting.</p>
         * 
         * <strong>example:</strong>
         * <p>A4EB8B1C-1DEC-5E18-BCD0-D1BBB3936FA7</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        public DescribeBackupPolicyResponseBody build() {
            return new DescribeBackupPolicyResponseBody(this);
        } 

    } 

    /**
     * 
     * {@link DescribeBackupPolicyResponseBody} extends {@link TeaModel}
     *
     * <p>DescribeBackupPolicyResponseBody</p>
     */
    public static class BackupPolicyDetail extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("ClientStatus")
        private String clientStatus;

        @com.aliyun.core.annotation.NameInMap("Id")
        private Long id;

        @com.aliyun.core.annotation.NameInMap("Name")
        private String name;

        @com.aliyun.core.annotation.NameInMap("Policy")
        private String policy;

        @com.aliyun.core.annotation.NameInMap("PolicyVersion")
        private String policyVersion;

        @com.aliyun.core.annotation.NameInMap("RegionId")
        private String regionId;

        @com.aliyun.core.annotation.NameInMap("Status")
        private String status;

        @com.aliyun.core.annotation.NameInMap("UuidList")
        private java.util.List<String> uuidList;

        private BackupPolicyDetail(Builder builder) {
            this.clientStatus = builder.clientStatus;
            this.id = builder.id;
            this.name = builder.name;
            this.policy = builder.policy;
            this.policyVersion = builder.policyVersion;
            this.regionId = builder.regionId;
            this.status = builder.status;
            this.uuidList = builder.uuidList;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static BackupPolicyDetail create() {
            return builder().build();
        }

        /**
         * @return clientStatus
         */
        public String getClientStatus() {
            return this.clientStatus;
        }

        /**
         * @return id
         */
        public Long getId() {
            return this.id;
        }

        /**
         * @return name
         */
        public String getName() {
            return this.name;
        }

        /**
         * @return policy
         */
        public String getPolicy() {
            return this.policy;
        }

        /**
         * @return policyVersion
         */
        public String getPolicyVersion() {
            return this.policyVersion;
        }

        /**
         * @return regionId
         */
        public String getRegionId() {
            return this.regionId;
        }

        /**
         * @return status
         */
        public String getStatus() {
            return this.status;
        }

        /**
         * @return uuidList
         */
        public java.util.List<String> getUuidList() {
            return this.uuidList;
        }

        public static final class Builder {
            private String clientStatus; 
            private Long id; 
            private String name; 
            private String policy; 
            private String policyVersion; 
            private String regionId; 
            private String status; 
            private java.util.List<String> uuidList; 

            private Builder() {
            } 

            private Builder(BackupPolicyDetail model) {
                this.clientStatus = model.clientStatus;
                this.id = model.id;
                this.name = model.name;
                this.policy = model.policy;
                this.policyVersion = model.policyVersion;
                this.regionId = model.regionId;
                this.status = model.status;
                this.uuidList = model.uuidList;
            } 

            /**
             * <p>The status of the anti-ransomware client. Valid values:</p>
             * <ul>
             * <li><p><strong>running</strong>: Normal.</p>
             * </li>
             * <li><p><strong>exception</strong>: Abnormal.</p>
             * </li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>running</p>
             */
            public Builder clientStatus(String clientStatus) {
                this.clientStatus = clientStatus;
                return this;
            }

            /**
             * <p>The ID of the anti-ransomware backup policy.</p>
             * 
             * <strong>example:</strong>
             * <p>51880</p>
             */
            public Builder id(Long id) {
                this.id = id;
                return this;
            }

            /**
             * <p>The policy name.</p>
             * 
             * <strong>example:</strong>
             * <p>testBuckUp</p>
             */
            public Builder name(String name) {
                this.name = name;
                return this;
            }

            /**
             * <p>The content of the anti-ransomware protection policy. This parameter is in JSON format. The following fields are included:</p>
             * <ul>
             * <li><strong>IsDefault</strong>: The type of the protection policy. Valid values:<ul>
             * <li><strong>1</strong>: recommended policy</li>
             * <li><strong>0</strong>: custom policy</li>
             * </ul>
             * </li>
             * <li><strong>Include</strong>: The file types to protect. If all file types are protected, this parameter is set to [].</li>
             * <li><strong>Source</strong>: The server folders to protect. If all folders are protected, this parameter is set to [].</li>
             * <li><strong>ExcludeSystemPath</strong>: Specifies whether to exclude specified folders. Set this parameter to <strong>true</strong> to exclude folders. If no folders need to be excluded, you do not need to configure this parameter.</li>
             * <li><strong>Exclude</strong>: The specified protection folder addresses. If no specific protection folder addresses are configured, this parameter is set to [].</li>
             * <li><strong>Schedule</strong>: Settings for the execution time and interval of the data backup task. Specify an off-peak hour that is not on the hour. Examples:<ul>
             * <li>Example 1: I|1583216092|P21D indicates that the data backup starts at 2020-03-03 14:14:52 and the backup policy executes at an interval of 3 weeks.</li>
             * <li>Example 2: I|1583216092|PT24H indicates that the data backup starts at 2020-03-03 14:14:52 and the backup policy executes at an interval of 24 hours.</li>
             * </ul>
             * </li>
             * <li><strong>Retention</strong>: Settings for the retention period of backup data, in days. 7 indicates 1 week, 365 indicates 1 year, and -1 indicates permanent retention.</li>
             * <li><strong>SpeedLimiter</strong>: Settings for the backup network bandwidth throttling. For example, 0:24:30720 indicates that the backup network bandwidth throttling is 30 MB/s from 00:00 to 24:00.</li>
             * <li><strong>UseVss</strong>: Specifies whether to enable the Volume Shadow Copy Service (VSS) feature for Windows. Valid values:<ul>
             * <li><strong>true</strong>: enabled</li>
             * <li><strong>false</strong>: not enabled</li>
             * </ul>
             * </li>
             * </ul>
             * <blockquote>
             * <p>The VSS feature is available only for Windows systems. After this feature is enabled, it effectively reduces the issue of individual file backup failures caused by process occupation. Enable this feature. After this feature is enabled, file backup for exFAT and FAT32 disk formats is not supported.</p>
             * </blockquote>
             * 
             * <strong>example:</strong>
             * <p>{
             *       &quot;Exclude&quot;: [
             *             &quot;/bin/&quot;,
             *             &quot;/usr/bin/&quot;,
             *             &quot;/sbin/&quot;,
             *             &quot;/boot/&quot;,
             *             &quot;/proc/&quot;,
             *             &quot;/sys/&quot;,
             *             &quot;/srv/&quot;,
             *             &quot;/lib/&quot;,
             *             &quot;/selinux/&quot;,
             *             &quot;/usr/sbin/&quot;,
             *             &quot;/run/&quot;,
             *             &quot;/lib32/&quot;,
             *             &quot;/lib64/&quot;,
             *             &quot;/lost+found/&quot;,
             *             &quot;/var/lib/kubelet/&quot;,
             *             &quot;/var/lib/ntp/proc&quot;,
             *             &quot;/var/lib/container&quot;,
             *             &quot;Windows\\&quot;,
             *             &quot;Python27\\&quot;,
             *             &quot;Program Files (x86)\\&quot;,
             *             &quot;Program Files\\&quot;,
             *             &quot;Boot\\&quot;,
             *             &quot;$RECYCLE.BIN&quot;,
             *             &quot;System Volume Information\\&quot;,
             *             &quot;Users\\Administrator\\NTUSER.DAT*&quot;,
             *             &quot;ProgramData\\&quot;,
             *             &quot;pagefile.sys&quot;,
             *             &quot;Users\\Default\\NTUSER.DAT*&quot;,
             *             &quot;Users\\Administrator\\ntuser.*&quot;
             *       ],
             *       &quot;ExcludeSystemPath&quot;: true,
             *       &quot;Include&quot;: [],
             *       &quot;IsDefault&quot;: 1,
             *       &quot;Retention&quot;: 7,
             *       &quot;Schedule&quot;: &quot;I|1630689360|PT24H&quot;,
             *       &quot;Source&quot;: [],
             *       &quot;SpeedLimiter&quot;: &quot;&quot;,
             *       &quot;UseVss&quot;: true
             * }</p>
             */
            public Builder policy(String policy) {
                this.policy = policy;
                return this;
            }

            /**
             * <p>The version of the protection policy. Valid values:</p>
             * <ul>
             * <li><strong>1.0.0</strong></li>
             * <li><strong>2.0.0</strong></li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>2.0.0</p>
             */
            public Builder policyVersion(String policyVersion) {
                this.policyVersion = policyVersion;
                return this;
            }

            /**
             * <p>The region ID of the backup service.</p>
             * 
             * <strong>example:</strong>
             * <p>cn-beijing</p>
             */
            public Builder regionId(String regionId) {
                this.regionId = regionId;
                return this;
            }

            /**
             * <p>The status of the anti-ransomware protection policy. Valid values:</p>
             * <ul>
             * <li><p><strong>enabled</strong>: The policy is manually enabled.</p>
             * </li>
             * <li><p><strong>disabled</strong>: The policy is manually disabled. After the policy is disabled, running backup tasks are stopped.</p>
             * </li>
             * <li><p><strong>closed</strong>: The policy is disabled by the system because the anti-ransomware capacity is exceeded.</p>
             * </li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>closed</p>
             */
            public Builder status(String status) {
                this.status = status;
                return this;
            }

            /**
             * <p>The UUIDs of the servers for which the backup policy is enabled.</p>
             */
            public Builder uuidList(java.util.List<String> uuidList) {
                this.uuidList = uuidList;
                return this;
            }

            public BackupPolicyDetail build() {
                return new BackupPolicyDetail(this);
            } 

        } 

    }
}
