// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link DescribeCloudVendorTrialConfigResponseBody} extends {@link TeaModel}
 *
 * <p>DescribeCloudVendorTrialConfigResponseBody</p>
 */
public class DescribeCloudVendorTrialConfigResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("Data")
    private Data data;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    private DescribeCloudVendorTrialConfigResponseBody(Builder builder) {
        this.data = builder.data;
        this.requestId = builder.requestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static DescribeCloudVendorTrialConfigResponseBody create() {
        return builder().build();
    }

    /**
     * @return data
     */
    public Data getData() {
        return this.data;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    public static final class Builder {
        private Data data; 
        private String requestId; 

        /**
         * <p>Returned data.</p>
         */
        public Builder data(Data data) {
            this.data = data;
            return this;
        }

        /**
         * <p>The ID of this request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.</p>
         * 
         * <strong>example:</strong>
         * <p>43313389-DED8-5BB7-8CB9-F22CDEB7****</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        public DescribeCloudVendorTrialConfigResponseBody build() {
            return new DescribeCloudVendorTrialConfigResponseBody(this);
        } 

    } 

    /**
     * 
     * {@link DescribeCloudVendorTrialConfigResponseBody} extends {@link TeaModel}
     *
     * <p>DescribeCloudVendorTrialConfigResponseBody</p>
     */
    public static class Data extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("AuthInfo")
        private String authInfo;

        @com.aliyun.core.annotation.NameInMap("Message")
        private String message;

        @com.aliyun.core.annotation.NameInMap("Status")
        private String status;

        private Data(Builder builder) {
            this.authInfo = builder.authInfo;
            this.message = builder.message;
            this.status = builder.status;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static Data create() {
            return builder().build();
        }

        /**
         * @return authInfo
         */
        public String getAuthInfo() {
            return this.authInfo;
        }

        /**
         * @return message
         */
        public String getMessage() {
            return this.message;
        }

        /**
         * @return status
         */
        public String getStatus() {
            return this.status;
        }

        public static final class Builder {
            private String authInfo; 
            private String message; 
            private String status; 

            /**
             * <p>Multi-cloud configuration information:</p>
             * <ul>
             * <li><em>AWS</em>: Output parameters sqsQueueName, sqsRegion</li>
             * <li><em>Tencent</em>: Output parameters kafkaUserName, kafkaBootstrapServers, kafkaTopic</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>{&quot;sqsRegion&quot;:&quot;us-west-2&quot;,&quot;sqsQueueName&quot;:&quot;****&quot;}</p>
             */
            public Builder authInfo(String authInfo) {
                this.authInfo = authInfo;
                return this;
            }

            /**
             * <p>Error message returned when connection fails.</p>
             * 
             * <strong>example:</strong>
             * <p>No relevant queue found</p>
             */
            public Builder message(String message) {
                this.message = message;
                return this;
            }

            /**
             * <p>The access status of the Trail configuration. Values:</p>
             * <ul>
             * <li><strong>init</strong>: Initialization in progress</li>
             * <li><strong>verify</strong>: Configuration verification in progress</li>
             * <li><strong>enable</strong>: Configuration enabled</li>
             * <li><strong>disable</strong>: Configuration disabled</li>
             * <li><strong>error</strong>: Configuration access error</li>
             * <li><strong>timeout</strong>: Configuration access timeout</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>init</p>
             */
            public Builder status(String status) {
                this.status = status;
                return this;
            }

            public Data build() {
                return new Data(this);
            } 

        } 

    }
}
