// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link GetAttackPathEventStatisticsResponseBody} extends {@link TeaModel}
 *
 * <p>GetAttackPathEventStatisticsResponseBody</p>
 */
public class GetAttackPathEventStatisticsResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    @com.aliyun.core.annotation.NameInMap("SeriousPathRiskNum")
    private Long seriousPathRiskNum;

    @com.aliyun.core.annotation.NameInMap("TotalAssetRiskNum")
    private Long totalAssetRiskNum;

    @com.aliyun.core.annotation.NameInMap("TotalPathRiskNum")
    private Long totalPathRiskNum;

    private GetAttackPathEventStatisticsResponseBody(Builder builder) {
        this.requestId = builder.requestId;
        this.seriousPathRiskNum = builder.seriousPathRiskNum;
        this.totalAssetRiskNum = builder.totalAssetRiskNum;
        this.totalPathRiskNum = builder.totalPathRiskNum;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static GetAttackPathEventStatisticsResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * @return seriousPathRiskNum
     */
    public Long getSeriousPathRiskNum() {
        return this.seriousPathRiskNum;
    }

    /**
     * @return totalAssetRiskNum
     */
    public Long getTotalAssetRiskNum() {
        return this.totalAssetRiskNum;
    }

    /**
     * @return totalPathRiskNum
     */
    public Long getTotalPathRiskNum() {
        return this.totalPathRiskNum;
    }

    public static final class Builder {
        private String requestId; 
        private Long seriousPathRiskNum; 
        private Long totalAssetRiskNum; 
        private Long totalPathRiskNum; 

        private Builder() {
        } 

        private Builder(GetAttackPathEventStatisticsResponseBody model) {
            this.requestId = model.requestId;
            this.seriousPathRiskNum = model.seriousPathRiskNum;
            this.totalAssetRiskNum = model.totalAssetRiskNum;
            this.totalPathRiskNum = model.totalPathRiskNum;
        } 

        /**
         * <p>The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and locate issues.</p>
         * 
         * <strong>example:</strong>
         * <p>89AD16CC-97EE-50F3-9B12-9E28E5C8****</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * <p>Number of attack paths that require urgent handling.</p>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        public Builder seriousPathRiskNum(Long seriousPathRiskNum) {
            this.seriousPathRiskNum = seriousPathRiskNum;
            return this;
        }

        /**
         * <p>Number of risky assets.</p>
         * 
         * <strong>example:</strong>
         * <p>5</p>
         */
        public Builder totalAssetRiskNum(Long totalAssetRiskNum) {
            this.totalAssetRiskNum = totalAssetRiskNum;
            return this;
        }

        /**
         * <p>Number of risk paths.</p>
         * 
         * <strong>example:</strong>
         * <p>10</p>
         */
        public Builder totalPathRiskNum(Long totalPathRiskNum) {
            this.totalPathRiskNum = totalPathRiskNum;
            return this;
        }

        public GetAttackPathEventStatisticsResponseBody build() {
            return new GetAttackPathEventStatisticsResponseBody(this);
        } 

    } 

}
