// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link GetConsoleFuncGrayStatusResponseBody} extends {@link TeaModel}
 *
 * <p>GetConsoleFuncGrayStatusResponseBody</p>
 */
public class GetConsoleFuncGrayStatusResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("Data")
    private Data data;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    private GetConsoleFuncGrayStatusResponseBody(Builder builder) {
        this.data = builder.data;
        this.requestId = builder.requestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static GetConsoleFuncGrayStatusResponseBody create() {
        return builder().build();
    }

    /**
     * @return data
     */
    public Data getData() {
        return this.data;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    public static final class Builder {
        private Data data; 
        private String requestId; 

        /**
         * <p>Return result.</p>
         */
        public Builder data(Data data) {
            this.data = data;
            return this;
        }

        /**
         * <p>The ID of this call request, which is a unique identifier generated by Alibaba Cloud for the request. It can be used to troubleshoot and pinpoint issues.</p>
         * 
         * <strong>example:</strong>
         * <p>5DFD6277-CC36-57F7-ACE6-F5952XXXXXXXX</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        public GetConsoleFuncGrayStatusResponseBody build() {
            return new GetConsoleFuncGrayStatusResponseBody(this);
        } 

    } 

    /**
     * 
     * {@link GetConsoleFuncGrayStatusResponseBody} extends {@link TeaModel}
     *
     * <p>GetConsoleFuncGrayStatusResponseBody</p>
     */
    public static class ExcludeApiList extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("Action")
        private String action;

        @com.aliyun.core.annotation.NameInMap("Code")
        private String code;

        @com.aliyun.core.annotation.NameInMap("Version")
        private String version;

        private ExcludeApiList(Builder builder) {
            this.action = builder.action;
            this.code = builder.code;
            this.version = builder.version;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static ExcludeApiList create() {
            return builder().build();
        }

        /**
         * @return action
         */
        public String getAction() {
            return this.action;
        }

        /**
         * @return code
         */
        public String getCode() {
            return this.code;
        }

        /**
         * @return version
         */
        public String getVersion() {
            return this.version;
        }

        public static final class Builder {
            private String action; 
            private String code; 
            private String version; 

            /**
             * <p>Action corresponding to the API.</p>
             * 
             * <strong>example:</strong>
             * <p>GetAttackTypeList</p>
             */
            public Builder action(String action) {
                this.action = action;
                return this;
            }

            /**
             * <p>Product Code.</p>
             * 
             * <strong>example:</strong>
             * <p>Sas</p>
             */
            public Builder code(String code) {
                this.code = code;
                return this;
            }

            /**
             * <p>API version.</p>
             * 
             * <strong>example:</strong>
             * <p>2017-11-10</p>
             */
            public Builder version(String version) {
                this.version = version;
                return this;
            }

            public ExcludeApiList build() {
                return new ExcludeApiList(this);
            } 

        } 

    }
    /**
     * 
     * {@link GetConsoleFuncGrayStatusResponseBody} extends {@link TeaModel}
     *
     * <p>GetConsoleFuncGrayStatusResponseBody</p>
     */
    public static class Data extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("ExcludeApiList")
        private java.util.List<ExcludeApiList> excludeApiList;

        @com.aliyun.core.annotation.NameInMap("Hit")
        private Boolean hit;

        private Data(Builder builder) {
            this.excludeApiList = builder.excludeApiList;
            this.hit = builder.hit;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static Data create() {
            return builder().build();
        }

        /**
         * @return excludeApiList
         */
        public java.util.List<ExcludeApiList> getExcludeApiList() {
            return this.excludeApiList;
        }

        /**
         * @return hit
         */
        public Boolean getHit() {
            return this.hit;
        }

        public static final class Builder {
            private java.util.List<ExcludeApiList> excludeApiList; 
            private Boolean hit; 

            /**
             * <p>List of APIs not hit.</p>
             */
            public Builder excludeApiList(java.util.List<ExcludeApiList> excludeApiList) {
                this.excludeApiList = excludeApiList;
                return this;
            }

            /**
             * <p>Whether it hits the gray status.</p>
             * 
             * <strong>example:</strong>
             * <p>true</p>
             */
            public Builder hit(Boolean hit) {
                this.hit = hit;
                return this;
            }

            public Data build() {
                return new Data(this);
            } 

        } 

    }
}
