// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link GetDockerhubImageRiskStatisticResponseBody} extends {@link TeaModel}
 *
 * <p>GetDockerhubImageRiskStatisticResponseBody</p>
 */
public class GetDockerhubImageRiskStatisticResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    @com.aliyun.core.annotation.NameInMap("RiskRankInfo")
    private RiskRankInfo riskRankInfo;

    private GetDockerhubImageRiskStatisticResponseBody(Builder builder) {
        this.requestId = builder.requestId;
        this.riskRankInfo = builder.riskRankInfo;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static GetDockerhubImageRiskStatisticResponseBody create() {
        return builder().build();
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * @return riskRankInfo
     */
    public RiskRankInfo getRiskRankInfo() {
        return this.riskRankInfo;
    }

    public static final class Builder {
        private String requestId; 
        private RiskRankInfo riskRankInfo; 

        /**
         * <p>The ID of this call request, which is a unique identifier generated by Alibaba Cloud for the request and can be used for troubleshooting and problem localization.</p>
         * 
         * <strong>example:</strong>
         * <p>7532B7EE-7CE7-5F4D-BF04-B12447DD****</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * <p>Risk source information.</p>
         */
        public Builder riskRankInfo(RiskRankInfo riskRankInfo) {
            this.riskRankInfo = riskRankInfo;
            return this;
        }

        public GetDockerhubImageRiskStatisticResponseBody build() {
            return new GetDockerhubImageRiskStatisticResponseBody(this);
        } 

    } 

    /**
     * 
     * {@link GetDockerhubImageRiskStatisticResponseBody} extends {@link TeaModel}
     *
     * <p>GetDockerhubImageRiskStatisticResponseBody</p>
     */
    public static class RiskRankInfo extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("Baseline")
        private Integer baseline;

        @com.aliyun.core.annotation.NameInMap("ScanTime")
        private Long scanTime;

        @com.aliyun.core.annotation.NameInMap("ScanTimeTimestamp")
        private Long scanTimeTimestamp;

        @com.aliyun.core.annotation.NameInMap("TotalScanned")
        private Integer totalScanned;

        @com.aliyun.core.annotation.NameInMap("VulAsap")
        private Integer vulAsap;

        private RiskRankInfo(Builder builder) {
            this.baseline = builder.baseline;
            this.scanTime = builder.scanTime;
            this.scanTimeTimestamp = builder.scanTimeTimestamp;
            this.totalScanned = builder.totalScanned;
            this.vulAsap = builder.vulAsap;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static RiskRankInfo create() {
            return builder().build();
        }

        /**
         * @return baseline
         */
        public Integer getBaseline() {
            return this.baseline;
        }

        /**
         * @return scanTime
         */
        public Long getScanTime() {
            return this.scanTime;
        }

        /**
         * @return scanTimeTimestamp
         */
        public Long getScanTimeTimestamp() {
            return this.scanTimeTimestamp;
        }

        /**
         * @return totalScanned
         */
        public Integer getTotalScanned() {
            return this.totalScanned;
        }

        /**
         * @return vulAsap
         */
        public Integer getVulAsap() {
            return this.vulAsap;
        }

        public static final class Builder {
            private Integer baseline; 
            private Long scanTime; 
            private Long scanTimeTimestamp; 
            private Integer totalScanned; 
            private Integer vulAsap; 

            /**
             * <p>Number of baseline issue risks.</p>
             * 
             * <strong>example:</strong>
             * <p>1</p>
             */
            public Builder baseline(Integer baseline) {
                this.baseline = baseline;
                return this;
            }

            /**
             * <p>Scan timestamp.</p>
             * 
             * <strong>example:</strong>
             * <p>1693997625000</p>
             */
            public Builder scanTime(Long scanTime) {
                this.scanTime = scanTime;
                return this;
            }

            /**
             * <p>Scan timestamp.</p>
             * 
             * <strong>example:</strong>
             * <p>1693997625000</p>
             */
            public Builder scanTimeTimestamp(Long scanTimeTimestamp) {
                this.scanTimeTimestamp = scanTimeTimestamp;
                return this;
            }

            /**
             * <p>Count of scanned Dockerhub images.</p>
             * 
             * <strong>example:</strong>
             * <p>1</p>
             */
            public Builder totalScanned(Integer totalScanned) {
                this.totalScanned = totalScanned;
                return this;
            }

            /**
             * <p>Number of high-risk vulnerabilities.</p>
             * 
             * <strong>example:</strong>
             * <p>1</p>
             */
            public Builder vulAsap(Integer vulAsap) {
                this.vulAsap = vulAsap;
                return this;
            }

            public RiskRankInfo build() {
                return new RiskRankInfo(this);
            } 

        } 

    }
}
