// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link GetFileDetectResultResponseBody} extends {@link TeaModel}
 *
 * <p>GetFileDetectResultResponseBody</p>
 */
public class GetFileDetectResultResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    @com.aliyun.core.annotation.NameInMap("ResultList")
    private java.util.List<ResultList> resultList;

    private GetFileDetectResultResponseBody(Builder builder) {
        this.requestId = builder.requestId;
        this.resultList = builder.resultList;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static GetFileDetectResultResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * @return resultList
     */
    public java.util.List<ResultList> getResultList() {
        return this.resultList;
    }

    public static final class Builder {
        private String requestId; 
        private java.util.List<ResultList> resultList; 

        private Builder() {
        } 

        private Builder(GetFileDetectResultResponseBody model) {
            this.requestId = model.requestId;
            this.resultList = model.resultList;
        } 

        /**
         * <p>The request ID, which is a unique identifier generated by Alibaba Cloud for this request. You can use it to troubleshoot issues.</p>
         * 
         * <strong>example:</strong>
         * <p>24A20733-10A0-4AF6-BE6B-E3322413BB68</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * <p>The list of detection results.</p>
         */
        public Builder resultList(java.util.List<ResultList> resultList) {
            this.resultList = resultList;
            return this;
        }

        public GetFileDetectResultResponseBody build() {
            return new GetFileDetectResultResponseBody(this);
        } 

    } 

    /**
     * 
     * {@link GetFileDetectResultResponseBody} extends {@link TeaModel}
     *
     * <p>GetFileDetectResultResponseBody</p>
     */
    public static class ResultList extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("Code")
        private String code;

        @com.aliyun.core.annotation.NameInMap("Compress")
        private Boolean compress;

        @com.aliyun.core.annotation.NameInMap("Ext")
        private String ext;

        @com.aliyun.core.annotation.NameInMap("HashKey")
        private String hashKey;

        @com.aliyun.core.annotation.NameInMap("Message")
        private String message;

        @com.aliyun.core.annotation.NameInMap("Result")
        private Integer result;

        @com.aliyun.core.annotation.NameInMap("Score")
        private Integer score;

        @com.aliyun.core.annotation.NameInMap("VirusType")
        private String virusType;

        private ResultList(Builder builder) {
            this.code = builder.code;
            this.compress = builder.compress;
            this.ext = builder.ext;
            this.hashKey = builder.hashKey;
            this.message = builder.message;
            this.result = builder.result;
            this.score = builder.score;
            this.virusType = builder.virusType;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static ResultList create() {
            return builder().build();
        }

        /**
         * @return code
         */
        public String getCode() {
            return this.code;
        }

        /**
         * @return compress
         */
        public Boolean getCompress() {
            return this.compress;
        }

        /**
         * @return ext
         */
        public String getExt() {
            return this.ext;
        }

        /**
         * @return hashKey
         */
        public String getHashKey() {
            return this.hashKey;
        }

        /**
         * @return message
         */
        public String getMessage() {
            return this.message;
        }

        /**
         * @return result
         */
        public Integer getResult() {
            return this.result;
        }

        /**
         * @return score
         */
        public Integer getScore() {
            return this.score;
        }

        /**
         * @return virusType
         */
        public String getVirusType() {
            return this.virusType;
        }

        public static final class Builder {
            private String code; 
            private Boolean compress; 
            private String ext; 
            private String hashKey; 
            private String message; 
            private Integer result; 
            private Integer score; 
            private String virusType; 

            private Builder() {
            } 

            private Builder(ResultList model) {
                this.code = model.code;
                this.compress = model.compress;
                this.ext = model.ext;
                this.hashKey = model.hashKey;
                this.message = model.message;
                this.result = model.result;
                this.score = model.score;
                this.virusType = model.virusType;
            } 

            /**
             * <p>The result code. A value of <strong>200</strong> indicates success. Any other value indicates failure. You can use this field to determine the cause of the failure.</p>
             * 
             * <strong>example:</strong>
             * <p>200</p>
             */
            public Builder code(String code) {
                this.code = code;
                return this;
            }

            /**
             * <p>Indicates whether the file is identified as a compressed archive.</p>
             * <ul>
             * <li><p><strong>true</strong>: Yes.</p>
             * </li>
             * <li><p><strong>false</strong>: No.</p>
             * </li>
             * </ul>
             * <blockquote>
             * <p>This parameter is not supported when Type is 6.</p>
             * </blockquote>
             * 
             * <strong>example:</strong>
             * <p>false</p>
             */
            public Builder compress(Boolean compress) {
                this.compress = compress;
                return this;
            }

            /**
             * <p>The extended information of the detection result.</p>
             * 
             * <strong>example:</strong>
             * <p>{
             *     &quot;HighLight&quot;:
             *     [
             *         [
             *             23245,
             *             23212
             *         ]
             *     ],
             *     &quot;FileLabel&quot;:
             *     [
             *         &quot;PE32&quot;,
             *         &quot;Zip&quot;,
             *         &quot;SFX&quot;,
             *         &quot;encrypted&quot;
             *     ]
             * }</p>
             */
            public Builder ext(String ext) {
                this.ext = ext;
                return this;
            }

            /**
             * <p>The file identifier.</p>
             * 
             * <strong>example:</strong>
             * <p>0a212417e65c26ff133cfff28f6c****</p>
             */
            public Builder hashKey(String hashKey) {
                this.hashKey = hashKey;
                return this;
            }

            /**
             * <p>The detailed information about the error code.</p>
             * 
             * <strong>example:</strong>
             * <p>successful</p>
             */
            public Builder message(String message) {
                this.message = message;
                return this;
            }

            /**
             * <p>The file detection result. Valid values:</p>
             * <ul>
             * <li><strong>0</strong>: Safe file.</li>
             * <li><strong>1</strong>: Suspicious file.</li>
             * <li><strong>3</strong>: Detection in progress. Wait for the detection to complete.</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>0</p>
             */
            public Builder result(Integer result) {
                this.result = result;
                return this;
            }

            /**
             * <p>The file detection score. The mapping between score ranges and risk levels is as follows:</p>
             * <ul>
             * <li>0–60: Safe.</li>
             * <li>61–70: Risky.</li>
             * <li>71–80: Suspicious.</li>
             * <li>81–100: Malicious.</li>
             * </ul>
             * <blockquote>
             * <p>Notice: A higher score indicates a more suspicious file.</p>
             * </blockquote>
             * <p>This field is returned only when Result is 1 (suspicious file). This field is not returned when Result is 0 or 3.</p>
             * 
             * <strong>example:</strong>
             * <p>100</p>
             */
            public Builder score(Integer score) {
                this.score = score;
                return this;
            }

            /**
             * <p>The virus type. Valid values:</p>
             * <ul>
             * <li><strong>Trojan</strong>: Trojan.</li>
             * <li><strong>WebShell</strong>: Web shell.</li>
             * <li><strong>Backdoor</strong>: Backdoor.</li>
             * <li><strong>RansomWare</strong>: Ransomware.</li>
             * <li><strong>Scanner</strong>: Scanner.</li>
             * <li><strong>Stealer</strong>: Credential stealer.</li>
             * <li><strong>Malbaseware</strong>: Contaminated base software.</li>
             * <li><strong>Hacktool</strong>: Hacking tool.</li>
             * <li><strong>Engtest</strong>: DPI engine test program.</li>
             * <li><strong>Downloader</strong>: Downloader Trojan.</li>
             * <li><strong>Virus</strong>: File infector virus.</li>
             * <li><strong>Miner</strong>: Mining programs.</li>
             * <li><strong>Worm</strong>: Worms.</li>
             * <li><strong>DDoS</strong>: DDoS Trojan.</li>
             * <li><strong>Malware</strong>: Malware.</li>
             * <li><strong>RiskWare</strong>: Riskware.</li>
             * <li><strong>Proxytool</strong>: Proxy tool.</li>
             * <li><strong>Suspicious</strong>: Suspicious program.</li>
             * <li><strong>MalScript</strong>: Malicious script.</li>
             * <li><strong>Rootkit</strong>: Rootkit.</li>
             * <li><strong>Exploit</strong>: Vulnerability exploits.</li>
             * </ul>
             * <blockquote>
             * <p>This parameter is not supported when Result is 0 or 3.</p>
             * </blockquote>
             * <p>This field is returned only when Result is 1 (suspicious file). This field is not returned when Result is 0 or 3.</p>
             * 
             * <strong>example:</strong>
             * <p>WebShell</p>
             */
            public Builder virusType(String virusType) {
                this.virusType = virusType;
                return this;
            }

            public ResultList build() {
                return new ResultList(this);
            } 

        } 

    }
}
