// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link ListCheckItemResponseBody} extends {@link TeaModel}
 *
 * <p>ListCheckItemResponseBody</p>
 */
public class ListCheckItemResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("CheckItems")
    private java.util.List<CheckItems> checkItems;

    @com.aliyun.core.annotation.NameInMap("PageInfo")
    private PageInfo pageInfo;

    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    private ListCheckItemResponseBody(Builder builder) {
        this.checkItems = builder.checkItems;
        this.pageInfo = builder.pageInfo;
        this.requestId = builder.requestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static ListCheckItemResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return checkItems
     */
    public java.util.List<CheckItems> getCheckItems() {
        return this.checkItems;
    }

    /**
     * @return pageInfo
     */
    public PageInfo getPageInfo() {
        return this.pageInfo;
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    public static final class Builder {
        private java.util.List<CheckItems> checkItems; 
        private PageInfo pageInfo; 
        private String requestId; 

        private Builder() {
        } 

        private Builder(ListCheckItemResponseBody model) {
            this.checkItems = model.checkItems;
            this.pageInfo = model.pageInfo;
            this.requestId = model.requestId;
        } 

        /**
         * <p>The list of check item information.</p>
         */
        public Builder checkItems(java.util.List<CheckItems> checkItems) {
            this.checkItems = checkItems;
            return this;
        }

        /**
         * <p>The page information in a paged query.</p>
         */
        public Builder pageInfo(PageInfo pageInfo) {
            this.pageInfo = pageInfo;
            return this;
        }

        /**
         * <p>The ID of the request, which is a unique identifier generated by Alibaba Cloud for the request. You can use this ID to troubleshoot issues.</p>
         * 
         * <strong>example:</strong>
         * <p>9F4E6157-9600-5588-86B9-38F09067****</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        public ListCheckItemResponseBody build() {
            return new ListCheckItemResponseBody(this);
        } 

    } 

    /**
     * 
     * {@link ListCheckItemResponseBody} extends {@link TeaModel}
     *
     * <p>ListCheckItemResponseBody</p>
     */
    public static class CustomConfigs extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("DefaultValue")
        private String defaultValue;

        @com.aliyun.core.annotation.NameInMap("Name")
        private String name;

        @com.aliyun.core.annotation.NameInMap("ShowName")
        private String showName;

        @com.aliyun.core.annotation.NameInMap("TypeDefine")
        private String typeDefine;

        @com.aliyun.core.annotation.NameInMap("Value")
        private String value;

        private CustomConfigs(Builder builder) {
            this.defaultValue = builder.defaultValue;
            this.name = builder.name;
            this.showName = builder.showName;
            this.typeDefine = builder.typeDefine;
            this.value = builder.value;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static CustomConfigs create() {
            return builder().build();
        }

        /**
         * @return defaultValue
         */
        public String getDefaultValue() {
            return this.defaultValue;
        }

        /**
         * @return name
         */
        public String getName() {
            return this.name;
        }

        /**
         * @return showName
         */
        public String getShowName() {
            return this.showName;
        }

        /**
         * @return typeDefine
         */
        public String getTypeDefine() {
            return this.typeDefine;
        }

        /**
         * @return value
         */
        public String getValue() {
            return this.value;
        }

        public static final class Builder {
            private String defaultValue; 
            private String name; 
            private String showName; 
            private String typeDefine; 
            private String value; 

            private Builder() {
            } 

            private Builder(CustomConfigs model) {
                this.defaultValue = model.defaultValue;
                this.name = model.name;
                this.showName = model.showName;
                this.typeDefine = model.typeDefine;
                this.value = model.value;
            } 

            /**
             * <p>The default value string of the custom configuration item for the check item.</p>
             * 
             * <strong>example:</strong>
             * <p>0</p>
             */
            public Builder defaultValue(String defaultValue) {
                this.defaultValue = defaultValue;
                return this;
            }

            /**
             * <p>The name of the custom check configuration.</p>
             * 
             * <strong>example:</strong>
             * <p>IPList</p>
             */
            public Builder name(String name) {
                this.name = name;
                return this;
            }

            /**
             * <p>The display name of the custom check configuration.</p>
             * 
             * <strong>example:</strong>
             * <p>IP List</p>
             */
            public Builder showName(String showName) {
                this.showName = showName;
                return this;
            }

            /**
             * <p>The JSON string that defines the type of the custom configuration item for the check item.</p>
             * 
             * <strong>example:</strong>
             * <p>{\&quot;type\&quot;:\&quot;LIST\&quot;,\&quot;range\&quot;:[1,512],\&quot;listType\&quot;:{\&quot;type\&quot;:\&quot;STRING\&quot;,\&quot;range\&quot;:[0,22]}}</p>
             */
            public Builder typeDefine(String typeDefine) {
                this.typeDefine = typeDefine;
                return this;
            }

            /**
             * <p>The user-configured value string of the custom configuration item for the check item.</p>
             * 
             * <strong>example:</strong>
             * <p>1</p>
             */
            public Builder value(String value) {
                this.value = value;
                return this;
            }

            public CustomConfigs build() {
                return new CustomConfigs(this);
            } 

        } 

    }
    /**
     * 
     * {@link ListCheckItemResponseBody} extends {@link TeaModel}
     *
     * <p>ListCheckItemResponseBody</p>
     */
    public static class Description extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("Type")
        private String type;

        @com.aliyun.core.annotation.NameInMap("Value")
        private String value;

        private Description(Builder builder) {
            this.type = builder.type;
            this.value = builder.value;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static Description create() {
            return builder().build();
        }

        /**
         * @return type
         */
        public String getType() {
            return this.type;
        }

        /**
         * @return value
         */
        public String getValue() {
            return this.value;
        }

        public static final class Builder {
            private String type; 
            private String value; 

            private Builder() {
            } 

            private Builder(Description model) {
                this.type = model.type;
                this.value = model.value;
            } 

            /**
             * <p>The type of the check description property. Valid values:</p>
             * <ul>
             * <li><strong>text</strong>: text</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>text</p>
             */
            public Builder type(String type) {
                this.type = type;
                return this;
            }

            /**
             * <p>The text content when the description type of the check item risk is text.</p>
             * 
             * <strong>example:</strong>
             * <p>Checks whether strict access control policies are configured. Requirements: 1. If no blacklists and whitelist are configured, configure a whitelist first. 2. If a blacklist is configured, find the blacklist in the list of access control policies. We recommend that you do not configure an empty blacklist. 3. If a whitelist is configured, find the whitelist in the list of access control policies. We recommend that you do not configure an empty whitelist. Make sure that the whitelist does not contain 0.0.0.0. You can add the following IP addresses to the whitelist: ${IPList}.</p>
             */
            public Builder value(String value) {
                this.value = value;
                return this;
            }

            public Description build() {
                return new Description(this);
            } 

        } 

    }
    /**
     * 
     * {@link ListCheckItemResponseBody} extends {@link TeaModel}
     *
     * <p>ListCheckItemResponseBody</p>
     */
    public static class CheckItems extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("CheckId")
        private Long checkId;

        @com.aliyun.core.annotation.NameInMap("CheckShowName")
        private String checkShowName;

        @com.aliyun.core.annotation.NameInMap("CheckType")
        private String checkType;

        @com.aliyun.core.annotation.NameInMap("CustomConfigs")
        private java.util.List<CustomConfigs> customConfigs;

        @com.aliyun.core.annotation.NameInMap("Description")
        private Description description;

        @com.aliyun.core.annotation.NameInMap("EstimatedCount")
        private Integer estimatedCount;

        @com.aliyun.core.annotation.NameInMap("InstanceEstimatedCount")
        private Integer instanceEstimatedCount;

        @com.aliyun.core.annotation.NameInMap("InstanceSubType")
        private String instanceSubType;

        @com.aliyun.core.annotation.NameInMap("InstanceType")
        private String instanceType;

        @com.aliyun.core.annotation.NameInMap("RiskLevel")
        private String riskLevel;

        @com.aliyun.core.annotation.NameInMap("SectionIds")
        private java.util.List<Long> sectionIds;

        @com.aliyun.core.annotation.NameInMap("Vendor")
        private String vendor;

        private CheckItems(Builder builder) {
            this.checkId = builder.checkId;
            this.checkShowName = builder.checkShowName;
            this.checkType = builder.checkType;
            this.customConfigs = builder.customConfigs;
            this.description = builder.description;
            this.estimatedCount = builder.estimatedCount;
            this.instanceEstimatedCount = builder.instanceEstimatedCount;
            this.instanceSubType = builder.instanceSubType;
            this.instanceType = builder.instanceType;
            this.riskLevel = builder.riskLevel;
            this.sectionIds = builder.sectionIds;
            this.vendor = builder.vendor;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static CheckItems create() {
            return builder().build();
        }

        /**
         * @return checkId
         */
        public Long getCheckId() {
            return this.checkId;
        }

        /**
         * @return checkShowName
         */
        public String getCheckShowName() {
            return this.checkShowName;
        }

        /**
         * @return checkType
         */
        public String getCheckType() {
            return this.checkType;
        }

        /**
         * @return customConfigs
         */
        public java.util.List<CustomConfigs> getCustomConfigs() {
            return this.customConfigs;
        }

        /**
         * @return description
         */
        public Description getDescription() {
            return this.description;
        }

        /**
         * @return estimatedCount
         */
        public Integer getEstimatedCount() {
            return this.estimatedCount;
        }

        /**
         * @return instanceEstimatedCount
         */
        public Integer getInstanceEstimatedCount() {
            return this.instanceEstimatedCount;
        }

        /**
         * @return instanceSubType
         */
        public String getInstanceSubType() {
            return this.instanceSubType;
        }

        /**
         * @return instanceType
         */
        public String getInstanceType() {
            return this.instanceType;
        }

        /**
         * @return riskLevel
         */
        public String getRiskLevel() {
            return this.riskLevel;
        }

        /**
         * @return sectionIds
         */
        public java.util.List<Long> getSectionIds() {
            return this.sectionIds;
        }

        /**
         * @return vendor
         */
        public String getVendor() {
            return this.vendor;
        }

        public static final class Builder {
            private Long checkId; 
            private String checkShowName; 
            private String checkType; 
            private java.util.List<CustomConfigs> customConfigs; 
            private Description description; 
            private Integer estimatedCount; 
            private Integer instanceEstimatedCount; 
            private String instanceSubType; 
            private String instanceType; 
            private String riskLevel; 
            private java.util.List<Long> sectionIds; 
            private String vendor; 

            private Builder() {
            } 

            private Builder(CheckItems model) {
                this.checkId = model.checkId;
                this.checkShowName = model.checkShowName;
                this.checkType = model.checkType;
                this.customConfigs = model.customConfigs;
                this.description = model.description;
                this.estimatedCount = model.estimatedCount;
                this.instanceEstimatedCount = model.instanceEstimatedCount;
                this.instanceSubType = model.instanceSubType;
                this.instanceType = model.instanceType;
                this.riskLevel = model.riskLevel;
                this.sectionIds = model.sectionIds;
                this.vendor = model.vendor;
            } 

            /**
             * <p>The ID of the check item.</p>
             * 
             * <strong>example:</strong>
             * <p>21</p>
             */
            public Builder checkId(Long checkId) {
                this.checkId = checkId;
                return this;
            }

            /**
             * <p>The name of the check item.</p>
             * 
             * <strong>example:</strong>
             * <p>IPv4 Access Control</p>
             */
            public Builder checkShowName(String checkShowName) {
                this.checkShowName = checkShowName;
                return this;
            }

            /**
             * <p>The source type of the Threat Detection Service check item. Valid values:</p>
             * <ul>
             * <li><strong>CUSTOM</strong>: user-defined</li>
             * <li><strong>SYSTEM</strong>: predefined by the Threat Detection Service platform</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>SYSTEM</p>
             */
            public Builder checkType(String checkType) {
                this.checkType = checkType;
                return this;
            }

            /**
             * <p>The list of custom check configuration information.</p>
             */
            public Builder customConfigs(java.util.List<CustomConfigs> customConfigs) {
                this.customConfigs = customConfigs;
                return this;
            }

            /**
             * <p>The description of the check item.</p>
             */
            public Builder description(Description description) {
                this.description = description;
                return this;
            }

            /**
             * <p>The estimated number of authorizations that the check item will consume.</p>
             * 
             * <strong>example:</strong>
             * <p>30</p>
             */
            public Builder estimatedCount(Integer estimatedCount) {
                this.estimatedCount = estimatedCount;
                return this;
            }

            /**
             * InstanceEstimatedCount.
             */
            public Builder instanceEstimatedCount(Integer instanceEstimatedCount) {
                this.instanceEstimatedCount = instanceEstimatedCount;
                return this;
            }

            /**
             * <p>The asset subtype of the cloud service. Valid values:</p>
             * <ul>
             * <li>If <strong>InstanceType</strong> is set to <strong>ECS</strong>, valid values of this parameter:<ul>
             * <li><strong>INSTANCE</strong></li>
             * <li><strong>DISK</strong></li>
             * <li><strong>SECURITY_GROUP</strong></li>
             * </ul>
             * </li>
             * <li>If <strong>InstanceType</strong> is set to <strong>ACR</strong>, valid values of this parameter:<ul>
             * <li><strong>REPOSITORY_ENTERPRISE</strong></li>
             * <li><strong>REPOSITORY_PERSON</strong></li>
             * </ul>
             * </li>
             * <li>If <strong>InstanceType</strong> is set to <strong>RAM</strong>, valid values of this parameter:<ul>
             * <li><strong>ALIAS</strong></li>
             * <li><strong>USER</strong></li>
             * <li><strong>POLICY</strong></li>
             * <li><strong>GROUP</strong></li>
             * </ul>
             * </li>
             * <li>If <strong>InstanceType</strong> is set to <strong>WAF</strong>, valid values of this parameter:<ul>
             * <li><strong>DOMAIN</strong></li>
             * </ul>
             * </li>
             * <li>If <strong>InstanceType</strong> is set to other values, valid values of this parameter:<ul>
             * <li><strong>INSTANCE</strong></li>
             * </ul>
             * </li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>INSTANCE</p>
             */
            public Builder instanceSubType(String instanceSubType) {
                this.instanceSubType = instanceSubType;
                return this;
            }

            /**
             * <p>The asset type of the cloud service. Valid values:</p>
             * <ul>
             * <li><strong>ECS</strong>: Elastic Compute Service server</li>
             * <li><strong>SLB</strong>: load balancing</li>
             * <li><strong>RDS</strong>: ApsaraDB RDS database</li>
             * <li><strong>MONGODB</strong>: ApsaraDB for MongoDB database</li>
             * <li><strong>KVSTORE</strong>: ApsaraDB for Redis database</li>
             * <li><strong>ACR</strong>: ACR</li>
             * <li><strong>CSK</strong>: CSK</li>
             * <li><strong>VPC</strong>: VPC</li>
             * <li><strong>ACTIONTRAIL</strong>: ActionTrail</li>
             * <li><strong>CDN</strong>: CDN</li>
             * <li><strong>CAS</strong>: Certificate Management Service (formerly SSL Certificates)</li>
             * <li><strong>RDC</strong>: Apsara Devops</li>
             * <li><strong>RAM</strong>: RAM</li>
             * <li><strong>DDOS</strong>: distributed deny-of-service</li>
             * <li><strong>WAF</strong>: WAF</li>
             * <li><strong>OSS</strong>: Access Control</li>
             * <li><strong>POLARDB</strong>: POLARDB</li>
             * <li><strong>POSTGRESQL</strong>: PostgreSQL</li>
             * <li><strong>MSE</strong>: MSE</li>
             * <li><strong>NAS</strong>: NAS</li>
             * <li><strong>SDDP</strong>: SDDP</li>
             * <li><strong>EIP</strong>: EIP</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>API_GATEWAY</p>
             */
            public Builder instanceType(String instanceType) {
                this.instanceType = instanceType;
                return this;
            }

            /**
             * <p>The risk level of the check item. Valid values:</p>
             * <ul>
             * <li><strong>HIGH</strong>: high</li>
             * <li><strong>MEDIUM</strong>: medium</li>
             * <li><strong>LOW</strong>: low</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>HIGH</p>
             */
            public Builder riskLevel(String riskLevel) {
                this.riskLevel = riskLevel;
                return this;
            }

            /**
             * <p>The list of section IDs associated with the check item.</p>
             */
            public Builder sectionIds(java.util.List<Long> sectionIds) {
                this.sectionIds = sectionIds;
                return this;
            }

            /**
             * <p>The cloud asset vendor. Valid values:</p>
             * <ul>
             * <li><strong>0</strong>: Alibaba Cloud asset</li>
             * <li><strong>1</strong>: asset outside the cloud</li>
             * <li><strong>2</strong>: IDC asset</li>
             * <li><strong>3</strong>, <strong>4</strong>, <strong>5</strong>, <strong>7</strong>: other cloud assets</li>
             * <li><strong>8</strong>: simple application server</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>0</p>
             */
            public Builder vendor(String vendor) {
                this.vendor = vendor;
                return this;
            }

            public CheckItems build() {
                return new CheckItems(this);
            } 

        } 

    }
    /**
     * 
     * {@link ListCheckItemResponseBody} extends {@link TeaModel}
     *
     * <p>ListCheckItemResponseBody</p>
     */
    public static class PageInfo extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("Count")
        private Integer count;

        @com.aliyun.core.annotation.NameInMap("CurrentPage")
        private Integer currentPage;

        @com.aliyun.core.annotation.NameInMap("PageSize")
        private Integer pageSize;

        @com.aliyun.core.annotation.NameInMap("TotalCount")
        private Integer totalCount;

        private PageInfo(Builder builder) {
            this.count = builder.count;
            this.currentPage = builder.currentPage;
            this.pageSize = builder.pageSize;
            this.totalCount = builder.totalCount;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static PageInfo create() {
            return builder().build();
        }

        /**
         * @return count
         */
        public Integer getCount() {
            return this.count;
        }

        /**
         * @return currentPage
         */
        public Integer getCurrentPage() {
            return this.currentPage;
        }

        /**
         * @return pageSize
         */
        public Integer getPageSize() {
            return this.pageSize;
        }

        /**
         * @return totalCount
         */
        public Integer getTotalCount() {
            return this.totalCount;
        }

        public static final class Builder {
            private Integer count; 
            private Integer currentPage; 
            private Integer pageSize; 
            private Integer totalCount; 

            private Builder() {
            } 

            private Builder(PageInfo model) {
                this.count = model.count;
                this.currentPage = model.currentPage;
                this.pageSize = model.pageSize;
                this.totalCount = model.totalCount;
            } 

            /**
             * <p>The number of entries on the current page in a paged query.</p>
             * 
             * <strong>example:</strong>
             * <p>10</p>
             */
            public Builder count(Integer count) {
                this.count = count;
                return this;
            }

            /**
             * <p>The page number of the current page in a paged query.</p>
             * 
             * <strong>example:</strong>
             * <p>1</p>
             */
            public Builder currentPage(Integer currentPage) {
                this.currentPage = currentPage;
                return this;
            }

            /**
             * <p>The number of entries per page.</p>
             * 
             * <strong>example:</strong>
             * <p>10</p>
             */
            public Builder pageSize(Integer pageSize) {
                this.pageSize = pageSize;
                return this;
            }

            /**
             * <p>The total number of entries returned.</p>
             * 
             * <strong>example:</strong>
             * <p>149</p>
             */
            public Builder totalCount(Integer totalCount) {
                this.totalCount = totalCount;
                return this;
            }

            public PageInfo build() {
                return new PageInfo(this);
            } 

        } 

    }
}
