// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.core.annotation.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * {@link ModifyNoticeConfigRequest} extends {@link RequestModel}
 *
 * <p>ModifyNoticeConfigRequest</p>
 */
public class ModifyNoticeConfigRequest extends Request {
    @Query
    @NameInMap("Project")
    private String project;

    @Query
    @NameInMap("Route")
    private Integer route;

    @Query
    @NameInMap("SourceIp")
    private String sourceIp;

    @Query
    @NameInMap("TimeLimit")
    private Integer timeLimit;

    private ModifyNoticeConfigRequest(Builder builder) {
        super(builder);
        this.project = builder.project;
        this.route = builder.route;
        this.sourceIp = builder.sourceIp;
        this.timeLimit = builder.timeLimit;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static ModifyNoticeConfigRequest create() {
        return builder().build();
    }

    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return project
     */
    public String getProject() {
        return this.project;
    }

    /**
     * @return route
     */
    public Integer getRoute() {
        return this.route;
    }

    /**
     * @return sourceIp
     */
    public String getSourceIp() {
        return this.sourceIp;
    }

    /**
     * @return timeLimit
     */
    public Integer getTimeLimit() {
        return this.timeLimit;
    }

    public static final class Builder extends Request.Builder<ModifyNoticeConfigRequest, Builder> {
        private String project; 
        private Integer route; 
        private String sourceIp; 
        private Integer timeLimit; 

        private Builder() {
            super();
        } 

        private Builder(ModifyNoticeConfigRequest request) {
            super(request);
            this.project = request.project;
            this.route = request.route;
            this.sourceIp = request.sourceIp;
            this.timeLimit = request.timeLimit;
        } 

        /**
         * The identifier of the notification item. Valid values:
         * <p>
         * 
         * *   **yundun\_security_Weekreport**: notification for vulnerabilities
         * *   **yundun\_sas\_antiransomware_task**: notification for results of restoration tasks
         * *   **sas_healthcheck**: notification for baseline checks
         * *   **sas_suspicious**: notification for alerts generated by Security Center
         * *   **yundun\_aegis\_AV_true**: notification for precision defense
         * *   **yundun\_sas\_ak_leakage**: notification for AccessKey pair leaks
         * *   **yundun\_sas\_config_alert**: notification for configuration assessment
         * *   **yundun\_sas\_vul_Emergency**: notification for urgent vulnerabilities
         * *   **yundun\_webguard_event**: notification for web tamper proofing
         * *   **yundun\_sas\_cloud\_native_firewall**: notification for alerts generated by the container firewall feature
         * *   **yundun\_sas\_cloud\_native\_firewall_Defense**: notification for proactive defense implemented by the container firewall feature
         * *   **yundun\_IP_Blocking**: notification for blocked brute-force attacks initiated from malicious IP addresses
         * *   **yundun\_sas\_anti\_virus_config**: notification for virus scan
         * *   **yundun\_sas_log**: notification for excess logs
         * *   **yundun\_honeypot_alarm**: notification for alerts generated by the honeypot feature
         * *   **aliyun\_rasp_alarm**: notification for alerts generated by the application security feature
         * *   **virusScheduleTask**: notification for completion of scheduled virus scans
         * *   **yundun\_anti_Virus**: notification that no security checks are performed
         * *   **sas_vulnerability**: notification for vulnerabilities
         * *   **weeklyreport**: notification for weekly reports
         * *   **agent**: notification that the Security Center agent is offline
         * *   **bruteforcesuccess**: notification for protection against brute-force attacks
         * *   **webshell**: notification for webshells
         * *   **suspicious**: notification for alerts generated by Server Guard
         * *   **patch**: deprecated
         * *   **remotelogin**: notification for remote logons
         * *   **health**: notification for security checks
         * *   **yundun\_sas\_cloudsiem_log**: notifications of insufficient threat analysis log capacity
         * 
         * > If the value is **yundun\_security_Weekreport**, weekly reports are sent to notify you of unhandled vulnerabilities.
         */
        public Builder project(String project) {
            this.putQueryParameter("Project", project);
            this.project = project;
            return this;
        }

        /**
         * The notification method. Valid values:
         * <p>
         * 
         * *   **1**: text message
         * *   **2**: email
         * *   **4**: internal message
         * *   **3**: text message and email
         * *   **5**: text message and internal message
         * *   **6**: email and internal message
         * *   **7**: text message, email, and internal message
         */
        public Builder route(Integer route) {
            this.putQueryParameter("Route", route);
            this.route = route;
            return this;
        }

        /**
         * The source IP address of the request.
         */
        public Builder sourceIp(String sourceIp) {
            this.putQueryParameter("SourceIp", sourceIp);
            this.sourceIp = sourceIp;
            return this;
        }

        /**
         * The time period during which Security Center sends notifications. Valid values:
         * <p>
         * 
         * *   **0**: any time
         * *   **1**: 08:00 to 22:00
         */
        public Builder timeLimit(Integer timeLimit) {
            this.putQueryParameter("TimeLimit", timeLimit);
            this.timeLimit = timeLimit;
            return this;
        }

        @Override
        public ModifyNoticeConfigRequest build() {
            return new ModifyNoticeConfigRequest(this);
        } 

    } 

}
