// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.sas20181203.models;

import com.aliyun.sdk.gateway.pop.*;
import darabonba.core.*;
import darabonba.core.async.*;
import darabonba.core.sync.*;
import darabonba.core.client.*;
import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * 
 * {@link UpdateMultiUserInstancesResponseBody} extends {@link TeaModel}
 *
 * <p>UpdateMultiUserInstancesResponseBody</p>
 */
public class UpdateMultiUserInstancesResponseBody extends TeaModel {
    @com.aliyun.core.annotation.NameInMap("RequestId")
    private String requestId;

    @com.aliyun.core.annotation.NameInMap("Result")
    private java.util.List<Result> result;

    private UpdateMultiUserInstancesResponseBody(Builder builder) {
        this.requestId = builder.requestId;
        this.result = builder.result;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static UpdateMultiUserInstancesResponseBody create() {
        return builder().build();
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return requestId
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * @return result
     */
    public java.util.List<Result> getResult() {
        return this.result;
    }

    public static final class Builder {
        private String requestId; 
        private java.util.List<Result> result; 

        private Builder() {
        } 

        private Builder(UpdateMultiUserInstancesResponseBody model) {
            this.requestId = model.requestId;
            this.result = model.result;
        } 

        /**
         * <p>The ID of this call request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem location.</p>
         * 
         * <strong>example:</strong>
         * <p>F8B6F758-BCD4-597A-8A2C-DA5A552C****</p>
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * <p>Request processing result.</p>
         */
        public Builder result(java.util.List<Result> result) {
            this.result = result;
            return this;
        }

        public UpdateMultiUserInstancesResponseBody build() {
            return new UpdateMultiUserInstancesResponseBody(this);
        } 

    } 

    /**
     * 
     * {@link UpdateMultiUserInstancesResponseBody} extends {@link TeaModel}
     *
     * <p>UpdateMultiUserInstancesResponseBody</p>
     */
    public static class Result extends TeaModel {
        @com.aliyun.core.annotation.NameInMap("AliUid")
        private Long aliUid;

        @com.aliyun.core.annotation.NameInMap("ErrorMessage")
        private String errorMessage;

        @com.aliyun.core.annotation.NameInMap("InstanceId")
        private String instanceId;

        @com.aliyun.core.annotation.NameInMap("UpdateStatus")
        private String updateStatus;

        private Result(Builder builder) {
            this.aliUid = builder.aliUid;
            this.errorMessage = builder.errorMessage;
            this.instanceId = builder.instanceId;
            this.updateStatus = builder.updateStatus;
        }

        public static Builder builder() {
            return new Builder();
        }

        public static Result create() {
            return builder().build();
        }

        /**
         * @return aliUid
         */
        public Long getAliUid() {
            return this.aliUid;
        }

        /**
         * @return errorMessage
         */
        public String getErrorMessage() {
            return this.errorMessage;
        }

        /**
         * @return instanceId
         */
        public String getInstanceId() {
            return this.instanceId;
        }

        /**
         * @return updateStatus
         */
        public String getUpdateStatus() {
            return this.updateStatus;
        }

        public static final class Builder {
            private Long aliUid; 
            private String errorMessage; 
            private String instanceId; 
            private String updateStatus; 

            private Builder() {
            } 

            private Builder(Result model) {
                this.aliUid = model.aliUid;
                this.errorMessage = model.errorMessage;
                this.instanceId = model.instanceId;
                this.updateStatus = model.updateStatus;
            } 

            /**
             * <p>User UID.</p>
             * 
             * <strong>example:</strong>
             * <p><strong><strong>185894</strong></strong></p>
             */
            public Builder aliUid(Long aliUid) {
                this.aliUid = aliUid;
                return this;
            }

            /**
             * <p>Error message returned when the call fails.</p>
             * 
             * <strong>example:</strong>
             * <p>Failed to update multi-user instance configuration</p>
             */
            public Builder errorMessage(String errorMessage) {
                this.errorMessage = errorMessage;
                return this;
            }

            /**
             * <p>The Cloud Security Center instance ID purchased by the member account.</p>
             * 
             * <strong>example:</strong>
             * <p>sas-p0anpb26****</p>
             */
            public Builder instanceId(String instanceId) {
                this.instanceId = instanceId;
                return this;
            }

            /**
             * <p>Update status. Values:  </p>
             * <ul>
             * <li><strong>1</strong>：Success </li>
             * <li><strong>2</strong>：Failure</li>
             * </ul>
             * 
             * <strong>example:</strong>
             * <p>1</p>
             */
            public Builder updateStatus(String updateStatus) {
                this.updateStatus = updateStatus;
                return this;
            }

            public Result build() {
                return new Result(this);
            } 

        } 

    }
}
