// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sdk.service.cloudsso20210515.models;

import darabonba.core.RequestModel;
import darabonba.core.TeaModel;
import com.aliyun.sdk.gateway.pop.models.*;

/**
 * {@link ResetUserPasswordRequest} extends {@link RequestModel}
 *
 * <p>ResetUserPasswordRequest</p>
 */
public class ResetUserPasswordRequest extends Request {
    @com.aliyun.core.annotation.Query
    @com.aliyun.core.annotation.NameInMap("DirectoryId")
    private String directoryId;

    @com.aliyun.core.annotation.Query
    @com.aliyun.core.annotation.NameInMap("GenerateRandomPassword")
    private Boolean generateRandomPassword;

    @com.aliyun.core.annotation.Query
    @com.aliyun.core.annotation.NameInMap("Password")
    private String password;

    @com.aliyun.core.annotation.Query
    @com.aliyun.core.annotation.NameInMap("RequirePasswordResetForNextLogin")
    private Boolean requirePasswordResetForNextLogin;

    @com.aliyun.core.annotation.Query
    @com.aliyun.core.annotation.NameInMap("UserId")
    private String userId;

    private ResetUserPasswordRequest(Builder builder) {
        super(builder);
        this.directoryId = builder.directoryId;
        this.generateRandomPassword = builder.generateRandomPassword;
        this.password = builder.password;
        this.requirePasswordResetForNextLogin = builder.requirePasswordResetForNextLogin;
        this.userId = builder.userId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static ResetUserPasswordRequest create() {
        return builder().build();
    }

    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * @return directoryId
     */
    public String getDirectoryId() {
        return this.directoryId;
    }

    /**
     * @return generateRandomPassword
     */
    public Boolean getGenerateRandomPassword() {
        return this.generateRandomPassword;
    }

    /**
     * @return password
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * @return requirePasswordResetForNextLogin
     */
    public Boolean getRequirePasswordResetForNextLogin() {
        return this.requirePasswordResetForNextLogin;
    }

    /**
     * @return userId
     */
    public String getUserId() {
        return this.userId;
    }

    public static final class Builder extends Request.Builder<ResetUserPasswordRequest, Builder> {
        private String directoryId; 
        private Boolean generateRandomPassword; 
        private String password; 
        private Boolean requirePasswordResetForNextLogin; 
        private String userId; 

        private Builder() {
            super();
        } 

        private Builder(ResetUserPasswordRequest request) {
            super(request);
            this.directoryId = request.directoryId;
            this.generateRandomPassword = request.generateRandomPassword;
            this.password = request.password;
            this.requirePasswordResetForNextLogin = request.requirePasswordResetForNextLogin;
            this.userId = request.userId;
        } 

        /**
         * The ID of the directory.
         */
        public Builder directoryId(String directoryId) {
            this.putQueryParameter("DirectoryId", directoryId);
            this.directoryId = directoryId;
            return this;
        }

        /**
         * Specifies whether to enable the system to automatically generate a new password. Valid values:
         * <p>
         * 
         * *   True: The new password is automatically generated by the system.
         * *   False: The new password must be manually specified. This is the default value.
         */
        public Builder generateRandomPassword(Boolean generateRandomPassword) {
            this.putQueryParameter("GenerateRandomPassword", generateRandomPassword);
            this.generateRandomPassword = generateRandomPassword;
            return this;
        }

        /**
         * The new password.
         * <p>
         * 
         * The password must contain the following types of characters: uppercase letters, lowercase letters, digits, and special characters.
         * 
         * The password must be 8 to 32 characters in length.
         * 
         * >  If you set `GenerateRandomPassword` to `False`, you must specify `Password` .
         */
        public Builder password(String password) {
            this.putQueryParameter("Password", password);
            this.password = password;
            return this;
        }

        /**
         * Specifies whether password reset is required upon the next logon. Valid values:
         * <p>
         * 
         * *   True: Password reset is required upon the next logon.
         * *   False: Password reset is not required upon the next logon. This is the default value.
         */
        public Builder requirePasswordResetForNextLogin(Boolean requirePasswordResetForNextLogin) {
            this.putQueryParameter("RequirePasswordResetForNextLogin", requirePasswordResetForNextLogin);
            this.requirePasswordResetForNextLogin = requirePasswordResetForNextLogin;
            return this;
        }

        /**
         * The ID of the user.
         */
        public Builder userId(String userId) {
            this.putQueryParameter("UserId", userId);
            this.userId = userId;
            return this;
        }

        @Override
        public ResetUserPasswordRequest build() {
            return new ResetUserPasswordRequest(this);
        } 

    } 

}
